#include "dudu/frontend/cli_options.hpp"
#include "dudu/lsp/language_server_diagnostics.hpp"
#include "dudu/lsp/language_server_macro_diagnostics.hpp"
#include "dudu/macro/macro_diagnostic_bridge.hpp"
#include "dudu/macro/macro_expansion_render.hpp"

#include <cassert>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

dudu::macro::ExpansionReport report_fixture() {
    namespace p = dudu::macro::protocol;
    p::FunctionDecl function;
    function.name = "to_json";

    p::Expression ready;
    ready.kind = p::ExpressionKind::Name;
    ready.name = "ready";
    p::Expression negated;
    negated.kind = p::ExpressionKind::Unary;
    negated.operator_name = "not";
    negated.children.push_back(ready);
    p::Statement check;
    check.kind = p::StatementKind::Expression;
    check.expression = negated;
    function.body.push_back(check);

    p::Expression count;
    count.kind = p::ExpressionKind::Name;
    count.name = "count";
    p::Expression one;
    one.kind = p::ExpressionKind::IntLiteral;
    one.value = "1";
    p::Statement increment;
    increment.kind = p::StatementKind::CompoundAssign;
    increment.target = count;
    increment.value = one;
    increment.operator_name = "+=";
    function.body.push_back(increment);
    p::Declaration declaration;
    declaration.kind = p::DeclarationKind::Function;
    declaration.function_decl = function;
    p::GeneratedDeclaration generated;
    generated.declaration = declaration;
    generated.origin.macro_name = "Json";
    generated.origin.range.file = "src/main.dd";
    generated.origin.range.start.line = 4;
    generated.origin.range.start.column = 1;

    p::Diagnostic note;
    note.severity = p::DiagnosticSeverity::Note;
    note.message = "field declared here";
    p::Diagnostic warning;
    warning.severity = p::DiagnosticSeverity::Warning;
    warning.code = "json.rename";
    warning.message = "field uses its source name";
    warning.notes.push_back(note);

    dudu::macro::ExpansionReport::Record record;
    record.macro_name = "Json";
    record.macro_identity = "macros.Json";
    record.target_module = "main";
    record.target_name = "Player";
    record.invocation.file = "src/main.dd";
    record.invocation.start.line = 3;
    record.invocation.start.column = 1;
    record.definition.file = "src/macros.dd";
    record.definition.start.line = 8;
    record.definition.start.column = 1;
    record.source_declaration = generated.origin.range;
    record.expansion.members.push_back(generated);
    record.expansion.diagnostics.push_back(warning);
    dudu::macro::ExpansionReport report;
    report.expansions.push_back(record);
    return report;
}

void test_render_filter_diagnostics_and_origins() {
    const dudu::macro::ExpansionReport report = report_fixture();
    const std::string plain = dudu::macro::render_expansion_report(report);
    assert(plain.find("@Json (macros.Json)") != std::string::npos);
    assert(plain.find("not ready") != std::string::npos);
    assert(plain.find("count += 1") != std::string::npos);
    assert(plain.find("notready") == std::string::npos);
    assert(plain.find("+==") == std::string::npos);
    assert(plain.find("warning[json.rename]") != std::string::npos);
    assert(plain.find("  note: field declared here") != std::string::npos);
    assert(plain.find("macro defined at") == std::string::npos);

    const std::string origins = dudu::macro::render_expansion_report(
        report, {.macro_filter = "Json", .show_origins = true});
    assert(origins.find("macro defined at src/macros.dd:8:1") != std::string::npos);
    assert(origins.find("source declaration at src/main.dd:4:1") != std::string::npos);
    assert(origins.find("generated by @Json from src/main.dd:4:1") != std::string::npos);

    const std::string missing = dudu::macro::render_expansion_report(
        report, {.macro_filter = "Debug", .show_origins = false});
    assert(missing == "# no matching macro expansions\n");
}

void test_expand_cli_options() {
    std::vector<std::string> storage = {"duc",     "expand", "main.dd",
                                        "--macro", "Json",   "--show-origins"};
    std::vector<char*> arguments;
    for (std::string& value : storage)
        arguments.push_back(value.data());
    const dudu::CliOptions options =
        dudu::parse_cli_options(static_cast<int>(arguments.size()), arguments.data(), false);
    assert(options.expand_macros);
    assert(options.input == "main.dd");
    assert(options.macro_filter == "Json");
    assert(options.show_macro_origins);
}

void test_macro_diagnostics_reach_lsp_with_related_notes() {
    const dudu::macro::ExpansionReport report = report_fixture();
    const dudu::Document document{.uri = "file:///src/main.dd", .path = "src/main.dd", .text = {}};
    const std::vector<dudu::Diagnostic> diagnostics =
        dudu::macro_diagnostics_for_document(report, document);
    assert(diagnostics.size() == 1);
    assert(diagnostics.front().severity == 2);
    assert(diagnostics.front().source == "dudu/macro");
    assert(diagnostics.front().related_information.size() == 1);
    const std::string json = dudu::diagnostic_json(diagnostics.front());
    assert(json.find("relatedInformation") != std::string::npos);
    assert(json.find("field declared here") != std::string::npos);
}

void test_macro_errors_preserve_nested_notes() {
    namespace p = dudu::macro::protocol;
    p::SourceRange invocation;
    invocation.file = "src/main.dd";
    invocation.start.line = 3;
    invocation.start.column = 1;
    p::Diagnostic note;
    note.severity = p::DiagnosticSeverity::Note;
    note.message = "invalid field declared here";
    note.range.file = "src/main.dd";
    note.range.start.line = 9;
    note.range.start.column = 5;
    p::Diagnostic error;
    error.severity = p::DiagnosticSeverity::Error;
    error.code = "json.field";
    error.message = "field cannot be serialized";
    error.notes.push_back(note);

    const dudu::CompileError compile_error =
        dudu::macro::compile_error_from_macro_diagnostic(error, invocation);
    assert(compile_error.code() == "json.field");
    assert(compile_error.location().line == 3);
    assert(compile_error.notes().size() == 1);
    assert(compile_error.notes().front().location.line == 9);
}

} // namespace

int main() {
    test_render_filter_diagnostics_and_origins();
    test_expand_cli_options();
    test_macro_diagnostics_reach_lsp_with_related_notes();
    test_macro_errors_preserve_nested_notes();
    return 0;
}
