#include "dudu/codegen/cpp_emit_prelude.hpp"

#include "dudu/codegen/cpp_emit_runtime_support.hpp"
#include "dudu/codegen/cpp_runtime_features.hpp"
#include "dudu/core/version.hpp"

#include <algorithm>
#include <cctype>
#include <map>
#include <sstream>

namespace dudu {
namespace {

std::string include_path(const ImportDecl& import) {
    if (import.native_include_style == NativeIncludeStyle::System) {
        return '<' + import.module_path + '>';
    }
    return '"' + import.module_path + '"';
}

std::string build_literal(const std::string& value) {
    if (value == "true" || value == "false") {
        return value;
    }
    if (!value.empty() && std::all_of(value.begin(), value.end(), [](char c) {
            return std::isdigit(static_cast<unsigned char>(c)) != 0;
        })) {
        return value;
    }
    if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
        return value;
    }
    return '"' + value + '"';
}

bool freestanding_like(const ModuleAst& module) {
    const auto found = module.build_values.find("TARGET_MODE");
    if (found == module.build_values.end()) {
        return false;
    }
    const std::string mode = build_literal(found->second);
    return mode == "\"freestanding\"" || mode == "\"embedded\"";
}

bool has_native_namespace(const ModuleAst& module, const std::string& name) {
    return std::any_of(module.native_namespaces.begin(), module.native_namespaces.end(),
                       [&](const NativeNamespaceDecl& ns) { return ns.name == name; });
}

template <typename Decl>
bool has_prefixed_native_symbol(const std::vector<Decl>& decls, const std::string& prefix) {
    const std::string marker = prefix + ".";
    return std::any_of(decls.begin(), decls.end(), [&](const Decl& decl) {
        return decl.name.substr(0, marker.size()) == marker;
    });
}

bool has_prefixed_native_symbol(const ModuleAst& module, const std::string& prefix) {
    return has_prefixed_native_symbol(module.native_types, prefix) ||
           has_prefixed_native_symbol(module.native_classes, prefix) ||
           has_prefixed_native_symbol(module.native_values, prefix) ||
           has_prefixed_native_symbol(module.native_functions, prefix) ||
           has_prefixed_native_symbol(module.native_macros, prefix);
}

bool stripped_native_import_alias(const ModuleAst& module, const ImportDecl& import) {
    return import.kind == ImportKind::ForeignCpp && !import.alias.empty() &&
           !has_native_namespace(module, import.alias) &&
           has_prefixed_native_symbol(module, import.alias);
}

std::string build_type(const std::string& literal, bool freestanding) {
    if (literal == "true" || literal == "false") {
        return "bool";
    }
    if (!literal.empty() && literal.front() == '"') {
        return freestanding ? "const char*" : "std::string_view";
    }
    return "int";
}

void emit_build_namespace(std::ostringstream& out, const ModuleAst& module) {
    std::map<std::string, std::string> values = {{"DEBUG", "false"},
                                                 {"RENDER_BACKEND", "\"vulkan\""}};
    for (const auto& [name, value] : module.build_values) {
        values[name] = value;
    }

    out << "namespace build {\n";
    const bool freestanding = freestanding_like(module);
    for (const auto& [name, value] : values) {
        const std::string literal = build_literal(value);
        out << "inline constexpr " << build_type(literal, freestanding) << ' ' << name << " = "
            << literal << ";\n";
    }
    out << "} // namespace build\n\n";
}

} // namespace

void emit_generated_banner(std::ostringstream& out) {
    out << "// Generated by Dudu " << kToolchainVersion << " (C++ schema "
        << kGeneratedCppSchemaVersion << ").\n";
}

std::vector<std::string> namespace_aliases(const ModuleAst& module) {
    std::vector<std::string> aliases;
    for (const NativeMacroDecl& macro : module.native_macros) {
        if (macro.name.find('.') != std::string::npos) {
            aliases.push_back("!" + macro.name);
        }
    }
    for (const ImportDecl& import : module.imports) {
        if (import.kind == ImportKind::ForeignCpp && !import.alias.empty()) {
            aliases.push_back(stripped_native_import_alias(module, import) ? "!" + import.alias
                                                                           : import.alias);
        } else if ((import.kind == ImportKind::ForeignC || import.kind == ImportKind::ForeignCxx) &&
                   !import.alias.empty()) {
            aliases.push_back("!" + import.alias);
        }
    }
    for (const std::string& prefix : module.module_strip_prefixes) {
        aliases.push_back("!" + prefix);
    }
    for (const NativeNamespaceDecl& ns : module.native_namespaces) {
        aliases.push_back(ns.name);
    }
    for (const ImportDecl& import : module.imports) {
        if (!stripped_native_import_alias(module, import)) {
            continue;
        }
        const std::string marker = import.alias + ".";
        for (const NativeNamespaceDecl& ns : module.native_namespaces) {
            if (ns.name.starts_with(marker)) {
                aliases.push_back(ns.name.substr(marker.size()));
            }
        }
    }
    return aliases;
}

namespace {

void emit_standard_includes(std::ostringstream& out, const ModuleAst& module,
                            const CppRuntimeFeatures& features) {
    out << "#include <cstddef>\n"
           "#include <cstdint>\n"
           "#include <type_traits>\n"
           "#include <utility>\n";
    auto include = [&](bool enabled, std::string_view header) {
        if (enabled) {
            out << "#include <" << header << ">\n";
        }
    };
    include(features.algorithm, "algorithm");
    include(features.fixed_array, "array");
    include(features.atomic, "atomic");
    include(features.assertions, "cassert");
    include(features.cstdlib, "cstdlib");
    include(features.function, "functional");
    include(features.array_view, "initializer_list");
    include(features.hosted_print && !freestanding_like(module), "iostream");
    include(features.optional, "optional");
    include(features.span, "span");
    include(features.exceptions, "stdexcept");
    include(features.string, "string");
    include(features.string_stream, "sstream");
    include(features.string_view, "string_view");
    include(features.unordered_map, "unordered_map");
    include(features.unordered_set, "unordered_set");
    include(features.variant || features.result, "variant");
    include(features.vector || features.array_view, "vector");
}

} // namespace

void emit_native_includes(std::ostringstream& out, const ModuleAst& module) {
    bool emitted = false;
    for (const ImportDecl& import : module.imports) {
        if (import.kind == ImportKind::ForeignC) {
            out << "extern \"C\" {\n"
                << "#include " << include_path(import) << '\n'
                << "}\n";
            emitted = true;
        } else if (import.kind == ImportKind::ForeignCxx || import.kind == ImportKind::ForeignCpp) {
            out << "#include " << include_path(import) << '\n';
            emitted = true;
        }
    }
    if (emitted) {
        out << '\n';
    }
}

namespace {

void emit_target_macros(std::ostringstream& out, const CppRuntimeFeatures& features) {
    if (!features.shader) {
        return;
    }
    out << "#ifndef DUDU_CUDA_GLOBAL\n"
           "#define DUDU_CUDA_GLOBAL\n"
           "#endif\n"
           "#ifndef DUDU_CUDA_DEVICE\n"
           "#define DUDU_CUDA_DEVICE\n"
           "#endif\n"
           "#ifndef DUDU_CUDA_HOST\n"
           "#define DUDU_CUDA_HOST\n"
           "#endif\n"
           "#ifndef DUDU_SHADER_COMPUTE\n"
           "#define DUDU_SHADER_COMPUTE\n"
           "#endif\n"
           "#ifndef DUDU_WORKGROUP_SIZE\n"
           "#define DUDU_WORKGROUP_SIZE(x, y, z)\n"
           "#endif\n";
    out << '\n';
}

void emit_runtime_support(std::ostringstream& out, const ModuleAst& module,
                          const CppRuntimeFeatures& features) {
    const bool freestanding = freestanding_like(module);
    const bool has_namespace_support =
        features.result || features.hosted_print || features.fixed_array || features.tuples ||
        features.indexing || features.array_view || features.strided_span;
    if (has_namespace_support) {
        out << "namespace dudu {\n";
        if (features.result) {
            emit_result_runtime_support(out);
        }
        if (features.hosted_print && !freestanding) {
            emit_print_runtime_support(out);
        }
        if (features.tuples) {
            emit_tuple_runtime_support(out);
        }
        if (features.fixed_array) {
            emit_fixed_array_runtime_support(out);
        }
        if (features.indexing) {
            emit_index_runtime_support(out);
        }
        if (features.array_view && !freestanding) {
            emit_array_view_runtime_support(out);
        }
        if (features.strided_span) {
            emit_strided_span_runtime_support(out);
        }
        out << "} // namespace dudu\n";
    }
    if (features.hosted_print && !freestanding) {
        out << "using dudu::print;\n";
    }
    if (features.min_max) {
        out << "using std::max;\nusing std::min;\n";
    }
    if (features.shader) {
        emit_shader_runtime_support(out);
    }
    emit_build_namespace(out, module);
}

} // namespace

void emit_prelude(std::ostringstream& out, const ModuleAst& module, bool include_native_imports) {
    const CppRuntimeFeatures features = cpp_runtime_features(module);
    emit_standard_includes(out, module, features);
    if (include_native_imports) {
        emit_native_includes(out, module);
    }
    emit_target_macros(out, features);
    emit_runtime_support(out, module, features);
}

} // namespace dudu
