#include "dudu/project/project_dependencies.hpp"

#include "dudu/core/file_io.hpp"
#include "dudu/native/native_build.hpp"

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>

namespace dudu {
namespace {

[[noreturn]] void fail_dependency(const std::string& message) {
    throw std::runtime_error(message);
}

std::string trim_newline(std::string value) {
    while (!value.empty() && (value.back() == '\n' || value.back() == '\r')) {
        value.pop_back();
    }
    return value;
}

std::string capture_command(const std::string& command) {
    FILE* pipe = popen((command + " 2>&1").c_str(), "r");
    if (pipe == nullptr) {
        fail_dependency("could not run command: " + command);
    }
    std::string out;
    char buffer[4096];
    while (fgets(buffer, sizeof(buffer), pipe) != nullptr) {
        out += buffer;
    }
    const int status = pclose(pipe);
    if (status != 0) {
        fail_dependency("command failed: " + command + "\n" + out);
    }
    return trim_newline(std::move(out));
}

void run_command_or_fail(const std::string& command, bool quiet, const std::string& message) {
    if (quiet) {
        try {
            (void)capture_command(command);
            return;
        } catch (const std::runtime_error& error) {
            fail_dependency(message + "\n" + error.what());
        }
    }
    if (std::system(command.c_str()) != 0) {
        fail_dependency(message + "\ncommand: " + command);
    }
}

std::string git_head_rev(const ProjectDependency& dependency, const std::filesystem::path& root) {
    try {
        return capture_command("git -C " + shell_quote_path(root) + " rev-parse HEAD");
    } catch (const std::runtime_error& error) {
        fail_dependency("could not resolve Git dependency '" + dependency.name +
                        "' commit\n" + error.what());
    }
}

std::string requested_git_ref(const ProjectDependency& dependency) {
    if (!dependency.rev.empty()) {
        return dependency.rev;
    }
    if (!dependency.tag.empty()) {
        return "tags/" + dependency.tag;
    }
    if (!dependency.branch.empty()) {
        return dependency.branch;
    }
    return {};
}

void checkout_git_ref(const ProjectDependency& dependency, const std::filesystem::path& root,
                      bool quiet) {
    const std::string ref = requested_git_ref(dependency);
    if (ref.empty()) {
        return;
    }
    run_command_or_fail("git -C " + shell_quote_path(root) + " checkout --quiet " +
                            shell_quote_arg(ref),
                        quiet,
                        "could not checkout Git dependency '" + dependency.name + "' ref '" + ref +
                            "'");
}

void ensure_git_dependency(ProjectDependency& dependency, const std::filesystem::path& root,
                           bool update, bool quiet) {
    if (!std::filesystem::exists(root)) {
        std::filesystem::create_directories(root.parent_path());
        run_command_or_fail("git clone --quiet " + shell_quote_arg(dependency.git) + " " +
                                shell_quote_path(root),
                            quiet,
                            "could not clone Git dependency '" + dependency.name + "' from " +
                                dependency.git);
        checkout_git_ref(dependency, root, quiet);
    } else {
        if (update) {
            run_command_or_fail("git -C " + shell_quote_path(root) + " fetch --quiet --tags",
                                quiet,
                                "could not fetch Git dependency '" + dependency.name + "'");
        }
        checkout_git_ref(dependency, root, quiet);
    }
    dependency.resolved_root = root;
    dependency.resolved_rev = git_head_rev(dependency, root);
}

std::string lock_text(const ProjectConfig& config) {
    std::ostringstream out;
    out << "# This file is generated by dudu deps fetch/build.\n";
    out << "# It pins Dudu source dependencies, not native C/C++ packages.\n\n";
    for (const auto& [name, dependency] : config.dependencies) {
        out << "[[deps]]\n";
        out << "name = \"" << name << "\"\n";
        out << "kind = \"" << dependency.kind << "\"\n";
        if (dependency.kind == "path") {
            out << "path = \"" << dependency.path.string() << "\"\n";
        } else if (dependency.kind == "git") {
            out << "git = \"" << dependency.git << "\"\n";
            if (!dependency.rev.empty()) {
                out << "requested = \"rev:" << dependency.rev << "\"\n";
            } else if (!dependency.tag.empty()) {
                out << "requested = \"tag:" << dependency.tag << "\"\n";
            } else if (!dependency.branch.empty()) {
                out << "requested = \"branch:" << dependency.branch << "\"\n";
            }
            out << "rev = \"" << dependency.resolved_rev << "\"\n";
        }
        out << "root = \"" << dependency.resolved_root.lexically_normal().string() << "\"\n\n";
    }
    return out.str();
}

void write_lock_if_changed(const ProjectConfig& config) {
    if (config.manifest_path.empty() || config.dependencies.empty()) {
        return;
    }
    const std::filesystem::path lock = config.project_dir / "dudu.lock";
    const std::string text = lock_text(config);
    if (try_read_text_file(lock) == text) {
        return;
    }
    std::ofstream out(lock, std::ios::binary);
    if (!out) {
        fail_dependency("could not write " + lock.string());
    }
    out << text;
}

void append_unique(std::vector<std::string>& target, const std::vector<std::string>& source) {
    for (const std::string& value : source) {
        if (std::find(target.begin(), target.end(), value) == target.end()) {
            target.push_back(value);
        }
    }
}

void append_unique_paths(std::vector<std::string>& target, const ProjectConfig& target_owner,
                         const ProjectConfig& source_owner,
                         const std::vector<std::string>& source) {
    for (const std::string& value : source) {
        const std::string absolute = project_path(source_owner, value).string();
        const bool present = std::any_of(target.begin(), target.end(), [&](const std::string& item) {
            return project_path(target_owner, item).lexically_normal() ==
                   std::filesystem::path(absolute).lexically_normal();
        });
        if (!present) {
            target.push_back(absolute);
        }
    }
}

void merge_native_inputs(ProjectConfig& target, const ProjectConfig& dependency) {
    append_unique_paths(target.c_sources, target, dependency, dependency.c_sources);
    append_unique_paths(target.cpp_sources, target, dependency, dependency.cpp_sources);
    append_unique_paths(target.include_dirs, target, dependency, dependency.include_dirs);
    append_unique_paths(target.lib_dirs, target, dependency, dependency.lib_dirs);
    append_unique_paths(target.pkg_config_paths, target, dependency, dependency.pkg_config_paths);
    append_unique(target.defines, dependency.defines);
    append_unique(target.flags, dependency.flags);
    append_unique(target.libs, dependency.libs);
    append_unique(target.link_flags, dependency.link_flags);
    append_unique(target.pkg_config_packages, dependency.pkg_config_packages);
}

} // namespace

std::filesystem::path dependency_cache_root(const ProjectConfig& config) {
    const std::filesystem::path root =
        config.project_dir.empty() ? std::filesystem::current_path() : config.project_dir;
    return root / ".dudu" / "deps";
}

std::filesystem::path dependency_package_root(const ProjectConfig& config,
                                              const ProjectDependency& dependency) {
    if (dependency.kind == "path") {
        return project_path(config, dependency.path);
    }
    if (dependency.kind == "git") {
        return dependency_cache_root(config) / dependency.name;
    }
    return {};
}

std::filesystem::path dependency_source_root(const std::filesystem::path& package_root) {
    const std::filesystem::path src = package_root / "src";
    return std::filesystem::exists(src) ? src : package_root;
}

void validate_dependency_package_root(const std::string& name, const std::filesystem::path& root) {
    if (!std::filesystem::exists(root / "dudu.toml")) {
        fail_dependency("Dudu dependency '" + name +
                        "' package root is missing dudu.toml: " + root.string());
    }
}

std::map<std::string, std::filesystem::path> dependency_module_roots(const ProjectConfig& config) {
    std::map<std::string, std::filesystem::path> out;
    for (const auto& [name, dependency] : config.dependencies) {
        const std::filesystem::path root = dependency_package_root(config, dependency);
        if (!root.empty()) {
            out[name] = dependency_source_root(root);
        }
    }
    return out;
}

void ensure_project_dependencies(ProjectConfig& config, bool update, bool quiet) {
    for (auto& [name, dependency] : config.dependencies) {
        const std::filesystem::path root = dependency_package_root(config, dependency);
        if (dependency.kind == "path") {
            if (!std::filesystem::exists(root)) {
                fail_dependency("Dudu dependency '" + name + "' path not found: " + root.string());
            }
            validate_dependency_package_root(name, root);
            dependency.resolved_root = root;
            continue;
        }
        if (dependency.kind == "git") {
            ensure_git_dependency(dependency, root, update, quiet);
            validate_dependency_package_root(name, root);
            continue;
        }
        fail_dependency("Dudu dependency '" + name + "' has unknown kind: " + dependency.kind);
    }
    write_lock_if_changed(config);
}

void merge_dependency_native_inputs(ProjectConfig& config) {
    for (const auto& [name, dependency] : config.dependencies) {
        const std::filesystem::path root = dependency_package_root(config, dependency);
        validate_dependency_package_root(name, root);
        const ProjectConfig package = parse_project_config(root / "dudu.toml");
        merge_native_inputs(config, package);
    }
}

} // namespace dudu
