#!/usr/bin/env python3
"""Generate Dudu macro protocol types and codecs from the public AST schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


PRIMITIVES = {
    "bool": "bool",
    "u32": "std::uint32_t",
    "u64": "std::uint64_t",
    "i64": "std::int64_t",
    "f64": "double",
    "string": "std::string",
    "bytes": "std::vector<std::uint8_t>",
}

DUDU_PRIMITIVES = {
    "bool": "bool",
    "u32": "u32",
    "u64": "u64",
    "i64": "i64",
    "f64": "f64",
    "string": "str",
    "bytes": "list[u8]",
}


def load_schema(path: Path) -> dict[str, Any]:
    schema = json.loads(path.read_text())
    if schema.get("schema") != "dudu.macro.ast":
        raise ValueError("unexpected macro schema identity")
    if not isinstance(schema.get("version"), int) or schema["version"] < 1:
        raise ValueError("macro schema version must be a positive integer")

    names: set[str] = set(PRIMITIVES)
    for section in ("enums", "structs"):
        for item in schema.get(section, []):
            name = item["name"]
            if name in names:
                raise ValueError(f"duplicate schema type: {name}")
            names.add(name)

    for struct in schema.get("structs", []):
        tags: set[int] = set()
        field_names: set[str] = set()
        for field in struct.get("fields", []):
            if field["type"] not in names:
                raise ValueError(f"unknown type {field['type']} in {struct['name']}")
            if field["name"] in field_names:
                raise ValueError(f"duplicate field {struct['name']}.{field['name']}")
            if field["tag"] in tags or field["tag"] <= 0:
                raise ValueError(f"invalid field tag in {struct['name']}")
            if field.get("optional") and field.get("repeated"):
                raise ValueError(f"field cannot be optional and repeated: {struct['name']}")
            field_names.add(field["name"])
            tags.add(field["tag"])
    return schema


def cpp_type(field: dict[str, Any], enum_names: set[str]) -> str:
    base = PRIMITIVES.get(field["type"], field["type"])
    if field["type"] in enum_names:
        base = field["type"]
    if field.get("repeated"):
        return f"std::vector<{base}>"
    if field.get("optional"):
        return f"std::optional<{base}>"
    return base


def dudu_type(field: dict[str, Any]) -> str:
    base = DUDU_PRIMITIVES.get(field["type"], field["type"])
    if field.get("repeated"):
        return f"list[{base}]"
    if field.get("optional"):
        return f"Option[{base}]"
    return base


def dudu_default(field: dict[str, Any], first_values: dict[str, str]) -> str:
    if field.get("repeated"):
        return "[]"
    if field.get("optional"):
        return "None"
    kind = field["type"]
    if kind == "bool":
        return "False"
    if kind in {"u32", "u64", "i64", "f64"}:
        return "0"
    if kind == "string":
        return "str()"
    if kind == "bytes":
        return "[]"
    if kind in first_values:
        return f"{kind}.{first_values[kind]}"
    return f"{kind}()"


def default_initializer(field: dict[str, Any], enum_names: set[str]) -> str:
    if field.get("optional") or field.get("repeated"):
        return "{}"
    kind = field["type"]
    if kind == "bool":
        return "false"
    if kind in {"u32", "u64", "i64", "f64"}:
        return "0"
    if kind in enum_names:
        return f"{kind}::{next(iter(()), '')}"  # replaced by caller
    return "{}"


def generate_header(schema: dict[str, Any]) -> str:
    enums = schema["enums"]
    structs = schema["structs"]
    enum_names = {enum["name"] for enum in enums}
    first_values = {enum["name"]: enum["values"][0] for enum in enums}
    lines = [
        "// Generated by scripts/generate_macro_ast.py. Do not edit.",
        "#pragma once",
        "",
        "#include \"dudu/macro/macro_wire.hpp\"",
        "",
        "#include <cstdint>",
        "#include <optional>",
        "#include <span>",
        "#include <string>",
        "#include <vector>",
        "",
        "namespace dudu::macro::protocol {",
        "",
        f"inline constexpr std::uint32_t schema_version = {schema['version']};",
        "inline constexpr std::uint32_t protocol_version = 1;",
        "",
    ]
    for enum in enums:
        lines.append(f"enum class {enum['name']} : std::uint32_t {{")
        for index, value in enumerate(enum["values"]):
            lines.append(f"    {value} = {index},")
        lines.extend(["};", ""])
    for struct in structs:
        lines.append(f"struct {struct['name']} {{")
        for field in struct["fields"]:
            initializer = default_initializer(field, enum_names)
            if field["type"] in enum_names and not field.get("optional") and not field.get("repeated"):
                initializer = f"{field['type']}::{first_values[field['type']]}"
            lines.append(f"    {cpp_type(field, enum_names)} {field['name']} = {initializer};")
        lines.extend(["};", ""])
    for struct in structs:
        name = struct["name"]
        lines.append(f"std::vector<std::uint8_t> encode(const {name}& value);")
        lines.append(
            f"{name} decode_{name}(std::span<const std::uint8_t> bytes, "
            "const wire::DecodeLimits& limits = {});"
        )
    lines.extend(["", "} // namespace dudu::macro::protocol", ""])
    return "\n".join(lines)


def field_encode(field: dict[str, Any], enum_names: set[str], value: str) -> str:
    tag = field["tag"]
    kind = field["type"]
    if kind in enum_names:
        return f"writer.write_varint({tag}, static_cast<std::uint64_t>({value}));"
    if kind in {"bool", "u32", "u64"}:
        return f"writer.write_varint({tag}, static_cast<std::uint64_t>({value}));"
    if kind == "i64":
        return f"writer.write_signed({tag}, {value});"
    if kind == "f64":
        return f"writer.write_double({tag}, {value});"
    if kind == "string":
        return f"writer.write_string({tag}, {value});"
    if kind == "bytes":
        return f"writer.write_bytes({tag}, {value});"
    return f"writer.write_message({tag}, [&](wire::Writer& nested) {{ encode_into(nested, {value}); }});"


def field_decode(field: dict[str, Any], enum_names: set[str], target: str) -> list[str]:
    kind = field["type"]
    if kind in enum_names:
        expr = f"static_cast<{kind}>(reader.read_varint(field_type))"
    elif kind == "bool":
        expr = "reader.read_varint(field_type) != 0"
    elif kind == "u32":
        expr = "reader.read_u32(field_type)"
    elif kind == "u64":
        expr = "reader.read_varint(field_type)"
    elif kind == "i64":
        expr = "reader.read_signed(field_type)"
    elif kind == "f64":
        expr = "reader.read_double(field_type)"
    elif kind == "string":
        expr = "reader.read_string(field_type)"
    elif kind == "bytes":
        expr = "reader.read_bytes(field_type)"
    else:
        expr = f"decode_{kind}_from(reader.read_message(field_type))"
    if field.get("repeated"):
        return [f"value.{target}.push_back({expr});"]
    return [f"value.{target} = {expr};"]


def generate_cpp(schema: dict[str, Any]) -> str:
    structs = schema["structs"]
    enum_names = {enum["name"] for enum in schema["enums"]}
    lines = [
        "// Generated by scripts/generate_macro_ast.py. Do not edit.",
        "#include \"dudu/macro/macro_protocol_generated.hpp\"",
        "",
        "namespace dudu::macro::protocol {",
        "namespace {",
        "",
    ]
    for struct in structs:
        lines.append(f"void encode_into(wire::Writer& writer, const {struct['name']}& value);")
        lines.append(f"{struct['name']} decode_{struct['name']}_from(wire::Reader reader);")
    lines.append("")
    for struct in structs:
        name = struct["name"]
        lines.append(f"void encode_into(wire::Writer& writer, const {name}& value) {{")
        for field in struct["fields"]:
            access = f"value.{field['name']}"
            statement = field_encode(field, enum_names, access)
            if field.get("repeated"):
                lines.append(f"    for (const auto& item : {access}) {{")
                lines.append("        " + field_encode(field, enum_names, "item"))
                lines.append("    }")
            elif field.get("optional"):
                lines.append(f"    if ({access}.has_value()) {{")
                lines.append("        " + field_encode(field, enum_names, f"*{access}"))
                lines.append("    }")
            elif field["type"] in {"string", "bytes"}:
                lines.append(f"    if (!{access}.empty()) {{")
                lines.append("        " + statement)
                lines.append("    }")
            else:
                lines.append("    " + statement)
        lines.extend(["}", ""])

        lines.append(f"{name} decode_{name}_from(wire::Reader reader) {{")
        lines.append(f"    {name} value;")
        lines.append("    std::uint32_t tag = 0;")
        lines.append("    wire::FieldType field_type = wire::FieldType::Varint;")
        lines.append("    while (reader.next(tag, field_type)) {")
        lines.append("        switch (tag) {")
        for field in struct["fields"]:
            lines.append(f"        case {field['tag']}:")
            for statement in field_decode(field, enum_names, field["name"]):
                lines.append("            " + statement)
            lines.append("            break;")
        lines.extend([
            "        default:",
            "            reader.skip(field_type);",
            "            break;",
            "        }",
            "    }",
            "    return value;",
            "}",
            "",
        ])
    lines.append("} // namespace")
    lines.append("")
    for struct in structs:
        name = struct["name"]
        lines.extend([
            f"std::vector<std::uint8_t> encode(const {name}& value) {{",
            "    wire::Writer writer;",
            "    encode_into(writer, value);",
            "    return writer.take();",
            "}",
            "",
            f"{name} decode_{name}(std::span<const std::uint8_t> bytes,",
            "                       const wire::DecodeLimits& limits) {",
            f"    return decode_{name}_from(wire::Reader::root(bytes, limits));",
            "}",
            "",
        ])
    lines.extend(["} // namespace dudu::macro::protocol", ""])
    return "\n".join(lines)


def generate_dudu(schema: dict[str, Any]) -> str:
    first_values = {enum["name"]: enum["values"][0] for enum in schema["enums"]}
    lines = [
        "# Generated by scripts/generate_macro_ast.py. Do not edit.",
        "# Public macro AST schema version " + str(schema["version"]) + ".",
        "",
    ]
    for enum in schema["enums"]:
        lines.append(f"enum {enum['name']}:")
        for value in enum["values"]:
            lines.append(f"    {value}")
        lines.append("")
    for struct in schema["structs"]:
        lines.append(f"class {struct['name']}:")
        for field in struct["fields"]:
            lines.append(
                f"    {field['name']}: {dudu_type(field)} = {dudu_default(field, first_values)}"
            )
        lines.append("")
    lines.extend(
        [
            "def named_type(name: str) -> TypeRef:",
            "    return TypeRef(kind=TypeKind.Named, name=name)",
            "",
            "",
            "def generic_type(name: str, arguments: list[TypeRef]) -> TypeRef:",
            "    return TypeRef(kind=TypeKind.Template, name=name, children=arguments)",
            "",
            "",
            "def name_expression(name: str) -> Expression:",
            "    return Expression(kind=ExpressionKind.Name, name=name)",
            "",
            "",
            "def string_expression(value: str) -> Expression:",
            "    return Expression(kind=ExpressionKind.StringLiteral, value=value)",
            "",
            "",
            "def call_expression(callee: Expression, arguments: list[Expression]) -> Expression:",
            "    children = [callee]",
            "    for argument in arguments:",
            "        children.append(argument)",
            "    return Expression(kind=ExpressionKind.Call, children=children)",
            "",
            "",
            "def function_declaration(value: FunctionDecl) -> Declaration:",
            "    return Declaration(kind=DeclarationKind.Function, function_decl=value)",
            "",
            "",
            "def field_declaration(value: FieldDecl) -> Declaration:",
            "    return Declaration(kind=DeclarationKind.Field, field_decl=value)",
            "",
            "",
            "def expansion() -> Expansion:",
            "    return Expansion()",
            "",
            "",
            "def generated(declaration: Declaration, origin: SourceOrigin) -> GeneratedDeclaration:",
            "    return GeneratedDeclaration(declaration=declaration, origin=origin)",
            "",
            "",
            "def error(location: SourceRange, message: str) -> Diagnostic:",
            "    return Diagnostic(",
            "        severity=DiagnosticSeverity.Error,",
            '        code="dudu.macro",',
            "        message=message,",
            "        range=location,",
            "    )",
            "",
        ]
    )
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    content = content.rstrip() + "\n"
    if check:
        return path.exists() and path.read_text() == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--cpp-header", type=Path, required=True)
    parser.add_argument("--cpp-source", type=Path, required=True)
    parser.add_argument("--dudu-sdk", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    schema = load_schema(args.schema)
    outputs = [
        (args.cpp_header, generate_header(schema)),
        (args.cpp_source, generate_cpp(schema)),
        (args.dudu_sdk, generate_dudu(schema)),
    ]
    stale = [str(path) for path, content in outputs if not write_or_check(path, content, args.check)]
    if stale:
        print("generated macro AST files are stale:")
        for path in stale:
            print(f"  {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
