// Generated by scripts/generate_macro_ast.py. Do not edit.
#pragma once

#include "dudu/ast.hpp"
#include "dudu/macro/macro_protocol_generated.hpp"

namespace dudu::macro::sdk_bridge {

DuduDuduAstVisibility from_protocol(protocol::Visibility input);
protocol::Visibility to_protocol(DuduDuduAstVisibility input);
DuduDuduAstDeclarationKind from_protocol(protocol::DeclarationKind input);
protocol::DeclarationKind to_protocol(DuduDuduAstDeclarationKind input);
DuduDuduAstTypeKind from_protocol(protocol::TypeKind input);
protocol::TypeKind to_protocol(DuduDuduAstTypeKind input);
DuduDuduAstExpressionKind from_protocol(protocol::ExpressionKind input);
protocol::ExpressionKind to_protocol(DuduDuduAstExpressionKind input);
DuduDuduAstStatementKind from_protocol(protocol::StatementKind input);
protocol::StatementKind to_protocol(DuduDuduAstStatementKind input);
DuduDuduAstDiagnosticSeverity from_protocol(protocol::DiagnosticSeverity input);
protocol::DiagnosticSeverity to_protocol(DuduDuduAstDiagnosticSeverity input);
DuduDuduAstOriginKind from_protocol(protocol::OriginKind input);
protocol::OriginKind to_protocol(DuduDuduAstOriginKind input);
DuduDuduAstCapabilityKind from_protocol(protocol::CapabilityKind input);
protocol::CapabilityKind to_protocol(DuduDuduAstCapabilityKind input);
DuduDuduAstMessageKind from_protocol(protocol::MessageKind input);
protocol::MessageKind to_protocol(DuduDuduAstMessageKind input);
DuduDuduAstSourcePosition from_protocol(const protocol::SourcePosition& input);
protocol::SourcePosition to_protocol(const DuduDuduAstSourcePosition& input);
DuduDuduAstSourceRange from_protocol(const protocol::SourceRange& input);
protocol::SourceRange to_protocol(const DuduDuduAstSourceRange& input);
DuduDuduAstSymbolIdentity from_protocol(const protocol::SymbolIdentity& input);
protocol::SymbolIdentity to_protocol(const DuduDuduAstSymbolIdentity& input);
DuduDuduAstTypeRef from_protocol(const protocol::TypeRef& input);
protocol::TypeRef to_protocol(const DuduDuduAstTypeRef& input);
DuduDuduAstExpression from_protocol(const protocol::Expression& input);
protocol::Expression to_protocol(const DuduDuduAstExpression& input);
DuduDuduAstStatement from_protocol(const protocol::Statement& input);
protocol::Statement to_protocol(const DuduDuduAstStatement& input);
DuduDuduAstAttributeArgument from_protocol(const protocol::AttributeArgument& input);
protocol::AttributeArgument to_protocol(const DuduDuduAstAttributeArgument& input);
DuduDuduAstAttribute from_protocol(const protocol::Attribute& input);
protocol::Attribute to_protocol(const DuduDuduAstAttribute& input);
DuduDuduAstGenericParameter from_protocol(const protocol::GenericParameter& input);
protocol::GenericParameter to_protocol(const DuduDuduAstGenericParameter& input);
DuduDuduAstParameter from_protocol(const protocol::Parameter& input);
protocol::Parameter to_protocol(const DuduDuduAstParameter& input);
DuduDuduAstFieldDecl from_protocol(const protocol::FieldDecl& input);
protocol::FieldDecl to_protocol(const DuduDuduAstFieldDecl& input);
DuduDuduAstFunctionDecl from_protocol(const protocol::FunctionDecl& input);
protocol::FunctionDecl to_protocol(const DuduDuduAstFunctionDecl& input);
DuduDuduAstEnumVariant from_protocol(const protocol::EnumVariant& input);
protocol::EnumVariant to_protocol(const DuduDuduAstEnumVariant& input);
DuduDuduAstEnumDecl from_protocol(const protocol::EnumDecl& input);
protocol::EnumDecl to_protocol(const DuduDuduAstEnumDecl& input);
DuduDuduAstConstantDecl from_protocol(const protocol::ConstantDecl& input);
protocol::ConstantDecl to_protocol(const DuduDuduAstConstantDecl& input);
DuduDuduAstClassDecl from_protocol(const protocol::ClassDecl& input);
protocol::ClassDecl to_protocol(const DuduDuduAstClassDecl& input);
DuduDuduAstImplementationDecl from_protocol(const protocol::ImplementationDecl& input);
protocol::ImplementationDecl to_protocol(const DuduDuduAstImplementationDecl& input);
DuduDuduAstDeclaration from_protocol(const protocol::Declaration& input);
protocol::Declaration to_protocol(const DuduDuduAstDeclaration& input);
DuduDuduAstSourceOrigin from_protocol(const protocol::SourceOrigin& input);
protocol::SourceOrigin to_protocol(const DuduDuduAstSourceOrigin& input);
DuduDuduAstGeneratedDeclaration from_protocol(const protocol::GeneratedDeclaration& input);
protocol::GeneratedDeclaration to_protocol(const DuduDuduAstGeneratedDeclaration& input);
DuduDuduAstDiagnostic from_protocol(const protocol::Diagnostic& input);
protocol::Diagnostic to_protocol(const DuduDuduAstDiagnostic& input);
DuduDuduAstGeneratedImport from_protocol(const protocol::GeneratedImport& input);
protocol::GeneratedImport to_protocol(const DuduDuduAstGeneratedImport& input);
DuduDuduAstExpansion from_protocol(const protocol::Expansion& input);
protocol::Expansion to_protocol(const DuduDuduAstExpansion& input);
DuduDuduAstCapability from_protocol(const protocol::Capability& input);
protocol::Capability to_protocol(const DuduDuduAstCapability& input);
DuduDuduAstMacroDescriptor from_protocol(const protocol::MacroDescriptor& input);
protocol::MacroDescriptor to_protocol(const DuduDuduAstMacroDescriptor& input);
DuduDuduAstMacroCatalog from_protocol(const protocol::MacroCatalog& input);
protocol::MacroCatalog to_protocol(const DuduDuduAstMacroCatalog& input);
DuduDuduAstHello from_protocol(const protocol::Hello& input);
protocol::Hello to_protocol(const DuduDuduAstHello& input);
DuduDuduAstHelloAck from_protocol(const protocol::HelloAck& input);
protocol::HelloAck to_protocol(const DuduDuduAstHelloAck& input);
DuduDuduAstExpansionRequest from_protocol(const protocol::ExpansionRequest& input);
protocol::ExpansionRequest to_protocol(const DuduDuduAstExpansionRequest& input);
DuduDuduAstExpansionResponse from_protocol(const protocol::ExpansionResponse& input);
protocol::ExpansionResponse to_protocol(const DuduDuduAstExpansionResponse& input);
DuduDuduAstWorkerError from_protocol(const protocol::WorkerError& input);
protocol::WorkerError to_protocol(const DuduDuduAstWorkerError& input);

} // namespace dudu::macro::sdk_bridge
