// Generated by scripts/generate_macro_ast.py. Do not edit.
#pragma once

#include "dudu/macro/macro_wire.hpp"

#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <vector>

namespace dudu::macro::protocol {

inline constexpr std::uint32_t schema_version = 3;
inline constexpr std::uint32_t protocol_version = 1;

enum class Visibility : std::uint32_t {
    Default = 0,
    Private = 1,
};

enum class DeclarationKind : std::uint32_t {
    Unknown = 0,
    Class = 1,
    Enum = 2,
    Function = 3,
    Field = 4,
    Constant = 5,
    Implementation = 6,
};

enum class TypeKind : std::uint32_t {
    Unknown = 0,
    Named = 1,
    Qualified = 2,
    Value = 3,
    Template = 4,
    Associated = 5,
    Pointer = 6,
    Reference = 7,
    Const = 8,
    Volatile = 9,
    Atomic = 10,
    Device = 11,
    Storage = 12,
    Shared = 13,
    Static = 14,
    FixedArray = 15,
    Function = 16,
    PackExpansion = 17,
    Shaped = 18,
    AssociatedTemplate = 19,
    NativeTransform = 20,
};

enum class ExpressionKind : std::uint32_t {
    Missing = 0,
    Name = 1,
    BoolLiteral = 2,
    IntLiteral = 3,
    FloatLiteral = 4,
    StringLiteral = 5,
    NoneLiteral = 6,
    Unary = 7,
    Binary = 8,
    Call = 9,
    TemplateCall = 10,
    Member = 11,
    Index = 12,
    ListLiteral = 13,
    DictLiteral = 14,
    DictEntry = 15,
    NamedArg = 16,
    Slice = 17,
    Ellipsis = 18,
    NewAxis = 19,
    PackExpansion = 20,
    SetLiteral = 21,
    TupleLiteral = 22,
    CppEscape = 23,
};

enum class StatementKind : std::uint32_t {
    Unknown = 0,
    Expression = 1,
    Variable = 2,
    Assign = 3,
    CompoundAssign = 4,
    Return = 5,
    If = 6,
    Elif = 7,
    Else = 8,
    Match = 9,
    Case = 10,
    While = 11,
    For = 12,
    Break = 13,
    Continue = 14,
    Try = 15,
    Except = 16,
    Raise = 17,
    Delete = 18,
    Assert = 19,
    DebugAssert = 20,
    CppEscape = 21,
    Pass = 22,
};

enum class DiagnosticSeverity : std::uint32_t {
    Note = 0,
    Warning = 1,
    Error = 2,
};

enum class OriginKind : std::uint32_t {
    Source = 0,
    MacroInvocation = 1,
    MacroDefinition = 2,
    Generated = 3,
};

enum class CapabilityKind : std::uint32_t {
    FsRead = 0,
    FsWrite = 1,
    EnvRead = 2,
    Process = 3,
    Network = 4,
    Clock = 5,
    Random = 6,
};

enum class MessageKind : std::uint32_t {
    Hello = 0,
    HelloAck = 1,
    Describe = 2,
    Catalog = 3,
    Expand = 4,
    ExpansionResult = 5,
    Shutdown = 6,
    WorkerError = 7,
};

struct SourcePosition {
    std::uint32_t line = 0;
    std::uint32_t column = 0;
    std::uint64_t offset = 0;
};

struct SourceRange {
    std::string file = {};
    SourcePosition start = {};
    SourcePosition end = {};
};

struct SymbolIdentity {
    std::string package = {};
    std::string module = {};
    std::string path = {};
    std::string native_identity = {};
};

struct TypeRef {
    TypeKind kind = TypeKind::Unknown;
    std::string name = {};
    std::string value = {};
    std::vector<TypeRef> children = {};
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
};

struct Expression {
    ExpressionKind kind = ExpressionKind::Missing;
    std::string name = {};
    std::string value = {};
    std::string operator_name = {};
    std::vector<Expression> children = {};
    std::vector<TypeRef> type_arguments = {};
    SourceRange range = {};
    std::optional<TypeRef> resolved_type = {};
    std::optional<SymbolIdentity> identity = {};
    std::vector<Expression> callee = {};
    std::vector<Expression> template_arguments = {};
};

struct Statement {
    StatementKind kind = StatementKind::Unknown;
    std::string name = {};
    std::optional<TypeRef> type = {};
    std::optional<Expression> expression = {};
    std::optional<Expression> value = {};
    std::optional<Expression> target = {};
    std::optional<Expression> condition = {};
    std::vector<Statement> children = {};
    SourceRange range = {};
    std::optional<Expression> message = {};
    std::optional<Expression> iterable = {};
    std::optional<Expression> pattern = {};
    std::optional<Expression> guard = {};
    std::string operator_name = {};
};

struct AttributeArgument {
    std::string name = {};
    Expression value = {};
    SourceRange range = {};
};

struct Attribute {
    std::string name = {};
    std::vector<AttributeArgument> arguments = {};
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
};

struct GenericParameter {
    std::string name = {};
    std::optional<TypeRef> type = {};
    std::optional<TypeRef> default_type = {};
    std::optional<Expression> default_value = {};
    bool variadic = false;
    SourceRange range = {};
};

struct Parameter {
    std::string name = {};
    TypeRef type = {};
    std::optional<Expression> default_value = {};
    bool variadic = false;
    SourceRange range = {};
};

struct FieldDecl {
    std::string name = {};
    TypeRef type = {};
    std::optional<Expression> value = {};
    std::vector<Attribute> attributes = {};
    std::string documentation = {};
    Visibility visibility = Visibility::Default;
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
};

struct FunctionDecl {
    std::string name = {};
    std::vector<GenericParameter> generic_parameters = {};
    std::vector<Parameter> parameters = {};
    std::optional<TypeRef> return_type = {};
    std::vector<Statement> body = {};
    std::vector<Attribute> attributes = {};
    std::string documentation = {};
    Visibility visibility = Visibility::Default;
    bool is_static = false;
    bool is_abstract = false;
    bool is_virtual = false;
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
};

struct EnumVariant {
    std::string name = {};
    std::vector<FieldDecl> fields = {};
    std::optional<Expression> value = {};
    std::vector<Attribute> attributes = {};
    SourceRange range = {};
};

struct EnumDecl {
    std::string name = {};
    std::vector<GenericParameter> generic_parameters = {};
    std::optional<TypeRef> underlying_type = {};
    std::vector<EnumVariant> variants = {};
    std::vector<Attribute> attributes = {};
    std::string documentation = {};
    Visibility visibility = Visibility::Default;
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
    std::vector<FunctionDecl> methods = {};
};

struct ConstantDecl {
    std::string name = {};
    TypeRef type = {};
    Expression value = {};
    std::vector<Attribute> attributes = {};
    std::string documentation = {};
    Visibility visibility = Visibility::Default;
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
};

struct ClassDecl {
    std::string name = {};
    std::vector<GenericParameter> generic_parameters = {};
    std::vector<TypeRef> bases = {};
    std::vector<FieldDecl> fields = {};
    std::vector<FunctionDecl> methods = {};
    std::vector<Attribute> attributes = {};
    std::string documentation = {};
    Visibility visibility = Visibility::Default;
    SourceRange range = {};
    std::optional<SymbolIdentity> identity = {};
    std::vector<ConstantDecl> constants = {};
    std::vector<ConstantDecl> static_fields = {};
};

struct ImplementationDecl {
    TypeRef contract = {};
    TypeRef target = {};
    std::vector<FunctionDecl> methods = {};
    SourceRange range = {};
};

struct Declaration {
    DeclarationKind kind = DeclarationKind::Unknown;
    std::optional<ClassDecl> class_decl = {};
    std::optional<EnumDecl> enum_decl = {};
    std::optional<FunctionDecl> function_decl = {};
    std::optional<FieldDecl> field_decl = {};
    std::optional<ConstantDecl> constant_decl = {};
    std::optional<ImplementationDecl> implementation_decl = {};
};

struct SourceOrigin {
    OriginKind kind = OriginKind::Source;
    SourceRange range = {};
    std::string macro_name = {};
    std::optional<SymbolIdentity> macro_identity = {};
    std::optional<std::uint64_t> parent = {};
};

struct GeneratedDeclaration {
    Declaration declaration = {};
    SourceOrigin origin = {};
};

struct Diagnostic {
    DiagnosticSeverity severity = DiagnosticSeverity::Note;
    std::string code = {};
    std::string message = {};
    SourceRange range = {};
    std::vector<Diagnostic> notes = {};
};

struct GeneratedImport {
    std::string module_path = {};
    std::string alias = {};
};

struct Expansion {
    std::vector<GeneratedDeclaration> members = {};
    std::vector<GeneratedDeclaration> siblings = {};
    std::vector<GeneratedDeclaration> implementations = {};
    std::vector<Diagnostic> diagnostics = {};
    std::vector<GeneratedImport> imports = {};
};

struct Capability {
    CapabilityKind kind = CapabilityKind::FsRead;
    std::vector<std::string> values = {};
};

struct MacroDescriptor {
    std::string name = {};
    std::string entry_point = {};
    DeclarationKind accepted_kind = DeclarationKind::Unknown;
    std::optional<ClassDecl> attribute_schema = {};
    SourceRange definition = {};
};

struct MacroCatalog {
    std::string package = {};
    std::string binary_identity = {};
    std::vector<MacroDescriptor> macros = {};
    std::vector<Capability> capabilities = {};
};

struct Hello {
    std::string compiler_version = {};
    std::uint32_t protocol_version = 0;
    std::uint32_t schema_version = 0;
    std::uint64_t max_frame_bytes = 0;
};

struct HelloAck {
    std::string worker_version = {};
    std::uint32_t protocol_version = 0;
    std::uint32_t schema_version = 0;
    bool accepted = false;
    std::string reason = {};
};

struct ExpansionRequest {
    std::string macro_name = {};
    Declaration declaration = {};
    SourceRange invocation = {};
    std::vector<AttributeArgument> compile_values = {};
};

struct ExpansionResponse {
    Expansion expansion = {};
    bool cacheable = false;
    std::vector<std::string> external_input_hashes = {};
    std::uint64_t execute_ns = 0;
};

struct WorkerError {
    std::string code = {};
    std::string message = {};
    std::vector<Diagnostic> diagnostics = {};
};

std::vector<std::uint8_t> encode(const SourcePosition& value);
SourcePosition decode_SourcePosition(std::span<const std::uint8_t> bytes,
                                     const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const SourcePosition& value);
std::vector<std::uint8_t> encode(const SourceRange& value);
SourceRange decode_SourceRange(std::span<const std::uint8_t> bytes,
                               const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const SourceRange& value);
std::vector<std::uint8_t> encode(const SymbolIdentity& value);
SymbolIdentity decode_SymbolIdentity(std::span<const std::uint8_t> bytes,
                                     const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const SymbolIdentity& value);
std::vector<std::uint8_t> encode(const TypeRef& value);
TypeRef decode_TypeRef(std::span<const std::uint8_t> bytes, const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const TypeRef& value);
std::vector<std::uint8_t> encode(const Expression& value);
Expression decode_Expression(std::span<const std::uint8_t> bytes,
                             const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Expression& value);
std::vector<std::uint8_t> encode(const Statement& value);
Statement decode_Statement(std::span<const std::uint8_t> bytes,
                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Statement& value);
std::vector<std::uint8_t> encode(const AttributeArgument& value);
AttributeArgument decode_AttributeArgument(std::span<const std::uint8_t> bytes,
                                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const AttributeArgument& value);
std::vector<std::uint8_t> encode(const Attribute& value);
Attribute decode_Attribute(std::span<const std::uint8_t> bytes,
                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Attribute& value);
std::vector<std::uint8_t> encode(const GenericParameter& value);
GenericParameter decode_GenericParameter(std::span<const std::uint8_t> bytes,
                                         const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const GenericParameter& value);
std::vector<std::uint8_t> encode(const Parameter& value);
Parameter decode_Parameter(std::span<const std::uint8_t> bytes,
                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Parameter& value);
std::vector<std::uint8_t> encode(const FieldDecl& value);
FieldDecl decode_FieldDecl(std::span<const std::uint8_t> bytes,
                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const FieldDecl& value);
std::vector<std::uint8_t> encode(const FunctionDecl& value);
FunctionDecl decode_FunctionDecl(std::span<const std::uint8_t> bytes,
                                 const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const FunctionDecl& value);
std::vector<std::uint8_t> encode(const EnumVariant& value);
EnumVariant decode_EnumVariant(std::span<const std::uint8_t> bytes,
                               const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const EnumVariant& value);
std::vector<std::uint8_t> encode(const EnumDecl& value);
EnumDecl decode_EnumDecl(std::span<const std::uint8_t> bytes,
                         const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const EnumDecl& value);
std::vector<std::uint8_t> encode(const ConstantDecl& value);
ConstantDecl decode_ConstantDecl(std::span<const std::uint8_t> bytes,
                                 const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const ConstantDecl& value);
std::vector<std::uint8_t> encode(const ClassDecl& value);
ClassDecl decode_ClassDecl(std::span<const std::uint8_t> bytes,
                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const ClassDecl& value);
std::vector<std::uint8_t> encode(const ImplementationDecl& value);
ImplementationDecl decode_ImplementationDecl(std::span<const std::uint8_t> bytes,
                                             const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const ImplementationDecl& value);
std::vector<std::uint8_t> encode(const Declaration& value);
Declaration decode_Declaration(std::span<const std::uint8_t> bytes,
                               const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Declaration& value);
std::vector<std::uint8_t> encode(const SourceOrigin& value);
SourceOrigin decode_SourceOrigin(std::span<const std::uint8_t> bytes,
                                 const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const SourceOrigin& value);
std::vector<std::uint8_t> encode(const GeneratedDeclaration& value);
GeneratedDeclaration decode_GeneratedDeclaration(std::span<const std::uint8_t> bytes,
                                                 const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const GeneratedDeclaration& value);
std::vector<std::uint8_t> encode(const Diagnostic& value);
Diagnostic decode_Diagnostic(std::span<const std::uint8_t> bytes,
                             const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Diagnostic& value);
std::vector<std::uint8_t> encode(const GeneratedImport& value);
GeneratedImport decode_GeneratedImport(std::span<const std::uint8_t> bytes,
                                       const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const GeneratedImport& value);
std::vector<std::uint8_t> encode(const Expansion& value);
Expansion decode_Expansion(std::span<const std::uint8_t> bytes,
                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Expansion& value);
std::vector<std::uint8_t> encode(const Capability& value);
Capability decode_Capability(std::span<const std::uint8_t> bytes,
                             const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Capability& value);
std::vector<std::uint8_t> encode(const MacroDescriptor& value);
MacroDescriptor decode_MacroDescriptor(std::span<const std::uint8_t> bytes,
                                       const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const MacroDescriptor& value);
std::vector<std::uint8_t> encode(const MacroCatalog& value);
MacroCatalog decode_MacroCatalog(std::span<const std::uint8_t> bytes,
                                 const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const MacroCatalog& value);
std::vector<std::uint8_t> encode(const Hello& value);
Hello decode_Hello(std::span<const std::uint8_t> bytes, const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const Hello& value);
std::vector<std::uint8_t> encode(const HelloAck& value);
HelloAck decode_HelloAck(std::span<const std::uint8_t> bytes,
                         const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const HelloAck& value);
std::vector<std::uint8_t> encode(const ExpansionRequest& value);
ExpansionRequest decode_ExpansionRequest(std::span<const std::uint8_t> bytes,
                                         const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const ExpansionRequest& value);
std::vector<std::uint8_t> encode(const ExpansionResponse& value);
ExpansionResponse decode_ExpansionResponse(std::span<const std::uint8_t> bytes,
                                           const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const ExpansionResponse& value);
std::vector<std::uint8_t> encode(const WorkerError& value);
WorkerError decode_WorkerError(std::span<const std::uint8_t> bytes,
                               const wire::DecodeLimits& limits = {});
std::size_t count_nodes(const WorkerError& value);

} // namespace dudu::macro::protocol
