// Generated by scripts/generate_macro_ast.py. Do not edit.
#include "dudu/macro/macro_protocol_generated.hpp"

namespace dudu::macro::protocol {
namespace {

void encode_into(wire::Writer& writer, const SourcePosition& value);
SourcePosition decode_SourcePosition_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const SourceRange& value);
SourceRange decode_SourceRange_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const SymbolIdentity& value);
SymbolIdentity decode_SymbolIdentity_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const TypeRef& value);
TypeRef decode_TypeRef_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Expression& value);
Expression decode_Expression_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Statement& value);
Statement decode_Statement_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const AttributeArgument& value);
AttributeArgument decode_AttributeArgument_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Attribute& value);
Attribute decode_Attribute_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const GenericParameter& value);
GenericParameter decode_GenericParameter_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Parameter& value);
Parameter decode_Parameter_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const FieldDecl& value);
FieldDecl decode_FieldDecl_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const FunctionDecl& value);
FunctionDecl decode_FunctionDecl_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const EnumVariant& value);
EnumVariant decode_EnumVariant_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const EnumDecl& value);
EnumDecl decode_EnumDecl_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const ConstantDecl& value);
ConstantDecl decode_ConstantDecl_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const ClassDecl& value);
ClassDecl decode_ClassDecl_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const ImplementationDecl& value);
ImplementationDecl decode_ImplementationDecl_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Declaration& value);
Declaration decode_Declaration_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const SourceOrigin& value);
SourceOrigin decode_SourceOrigin_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const GeneratedDeclaration& value);
GeneratedDeclaration decode_GeneratedDeclaration_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Diagnostic& value);
Diagnostic decode_Diagnostic_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Expansion& value);
Expansion decode_Expansion_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Capability& value);
Capability decode_Capability_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const MacroDescriptor& value);
MacroDescriptor decode_MacroDescriptor_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const MacroCatalog& value);
MacroCatalog decode_MacroCatalog_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const Hello& value);
Hello decode_Hello_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const HelloAck& value);
HelloAck decode_HelloAck_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const ExpansionRequest& value);
ExpansionRequest decode_ExpansionRequest_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const ExpansionResponse& value);
ExpansionResponse decode_ExpansionResponse_from(wire::Reader reader);
void encode_into(wire::Writer& writer, const WorkerError& value);
WorkerError decode_WorkerError_from(wire::Reader reader);

void encode_into(wire::Writer& writer, const SourcePosition& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.line));
    writer.write_varint(2, static_cast<std::uint64_t>(value.column));
    writer.write_varint(3, static_cast<std::uint64_t>(value.offset));
}

SourcePosition decode_SourcePosition_from(wire::Reader reader) {
    SourcePosition value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.line = reader.read_u32(field_type);
            break;
        case 2:
            value.column = reader.read_u32(field_type);
            break;
        case 3:
            value.offset = reader.read_varint(field_type);
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const SourceRange& value) {
    if (!value.file.empty()) {
        writer.write_string(1, value.file);
    }
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.start); });
    writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, value.end); });
}

SourceRange decode_SourceRange_from(wire::Reader reader) {
    SourceRange value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.file = reader.read_string(field_type);
            break;
        case 2:
            value.start = decode_SourcePosition_from(reader.read_message(field_type));
            break;
        case 3:
            value.end = decode_SourcePosition_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const SymbolIdentity& value) {
    if (!value.package.empty()) {
        writer.write_string(1, value.package);
    }
    if (!value.module.empty()) {
        writer.write_string(2, value.module);
    }
    if (!value.path.empty()) {
        writer.write_string(3, value.path);
    }
    if (!value.native_identity.empty()) {
        writer.write_string(4, value.native_identity);
    }
}

SymbolIdentity decode_SymbolIdentity_from(wire::Reader reader) {
    SymbolIdentity value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.package = reader.read_string(field_type);
            break;
        case 2:
            value.module = reader.read_string(field_type);
            break;
        case 3:
            value.path = reader.read_string(field_type);
            break;
        case 4:
            value.native_identity = reader.read_string(field_type);
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const TypeRef& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.kind));
    if (!value.name.empty()) {
        writer.write_string(2, value.name);
    }
    if (!value.value.empty()) {
        writer.write_string(3, value.value);
    }
    for (const auto& item : value.children) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
}

TypeRef decode_TypeRef_from(wire::Reader reader) {
    TypeRef value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.kind = static_cast<TypeKind>(reader.read_varint(field_type));
            break;
        case 2:
            value.name = reader.read_string(field_type);
            break;
        case 3:
            value.value = reader.read_string(field_type);
            break;
        case 4:
            value.children.push_back(decode_TypeRef_from(reader.read_message(field_type)));
            break;
        case 5:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 6:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Expression& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.kind));
    if (!value.name.empty()) {
        writer.write_string(2, value.name);
    }
    if (!value.value.empty()) {
        writer.write_string(3, value.value);
    }
    if (!value.operator_name.empty()) {
        writer.write_string(4, value.operator_name);
    }
    for (const auto& item : value.children) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.type_arguments) {
        writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    writer.write_message(7, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.resolved_type.has_value()) {
        writer.write_message(8, [&](wire::Writer& nested) { encode_into(nested, *value.resolved_type); });
    }
    if (value.identity.has_value()) {
        writer.write_message(9, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
    for (const auto& item : value.callee) {
        writer.write_message(10, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.template_arguments) {
        writer.write_message(11, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

Expression decode_Expression_from(wire::Reader reader) {
    Expression value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.kind = static_cast<ExpressionKind>(reader.read_varint(field_type));
            break;
        case 2:
            value.name = reader.read_string(field_type);
            break;
        case 3:
            value.value = reader.read_string(field_type);
            break;
        case 4:
            value.operator_name = reader.read_string(field_type);
            break;
        case 5:
            value.children.push_back(decode_Expression_from(reader.read_message(field_type)));
            break;
        case 6:
            value.type_arguments.push_back(decode_TypeRef_from(reader.read_message(field_type)));
            break;
        case 7:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 8:
            value.resolved_type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 9:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        case 10:
            value.callee.push_back(decode_Expression_from(reader.read_message(field_type)));
            break;
        case 11:
            value.template_arguments.push_back(decode_Expression_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Statement& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.kind));
    if (!value.name.empty()) {
        writer.write_string(2, value.name);
    }
    if (value.type.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.type); });
    }
    if (value.expression.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.expression); });
    }
    if (value.value.has_value()) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, *value.value); });
    }
    if (value.target.has_value()) {
        writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, *value.target); });
    }
    if (value.condition.has_value()) {
        writer.write_message(7, [&](wire::Writer& nested) { encode_into(nested, *value.condition); });
    }
    for (const auto& item : value.children) {
        writer.write_message(8, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    writer.write_message(9, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.message.has_value()) {
        writer.write_message(10, [&](wire::Writer& nested) { encode_into(nested, *value.message); });
    }
    if (value.iterable.has_value()) {
        writer.write_message(11, [&](wire::Writer& nested) { encode_into(nested, *value.iterable); });
    }
    if (value.pattern.has_value()) {
        writer.write_message(12, [&](wire::Writer& nested) { encode_into(nested, *value.pattern); });
    }
    if (value.guard.has_value()) {
        writer.write_message(13, [&](wire::Writer& nested) { encode_into(nested, *value.guard); });
    }
    if (!value.operator_name.empty()) {
        writer.write_string(14, value.operator_name);
    }
}

Statement decode_Statement_from(wire::Reader reader) {
    Statement value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.kind = static_cast<StatementKind>(reader.read_varint(field_type));
            break;
        case 2:
            value.name = reader.read_string(field_type);
            break;
        case 3:
            value.type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 4:
            value.expression = decode_Expression_from(reader.read_message(field_type));
            break;
        case 5:
            value.value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 6:
            value.target = decode_Expression_from(reader.read_message(field_type));
            break;
        case 7:
            value.condition = decode_Expression_from(reader.read_message(field_type));
            break;
        case 8:
            value.children.push_back(decode_Statement_from(reader.read_message(field_type)));
            break;
        case 9:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 10:
            value.message = decode_Expression_from(reader.read_message(field_type));
            break;
        case 11:
            value.iterable = decode_Expression_from(reader.read_message(field_type));
            break;
        case 12:
            value.pattern = decode_Expression_from(reader.read_message(field_type));
            break;
        case 13:
            value.guard = decode_Expression_from(reader.read_message(field_type));
            break;
        case 14:
            value.operator_name = reader.read_string(field_type);
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const AttributeArgument& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.value); });
    writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, value.range); });
}

AttributeArgument decode_AttributeArgument_from(wire::Reader reader) {
    AttributeArgument value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 3:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Attribute& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    for (const auto& item : value.arguments) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
}

Attribute decode_Attribute_from(wire::Reader reader) {
    Attribute value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.arguments.push_back(decode_AttributeArgument_from(reader.read_message(field_type)));
            break;
        case 3:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 4:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const GenericParameter& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    if (value.type.has_value()) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, *value.type); });
    }
    if (value.default_type.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.default_type); });
    }
    if (value.default_value.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.default_value); });
    }
    writer.write_varint(5, static_cast<std::uint64_t>(value.variadic));
    writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, value.range); });
}

GenericParameter decode_GenericParameter_from(wire::Reader reader) {
    GenericParameter value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 3:
            value.default_type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 4:
            value.default_value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 5:
            value.variadic = reader.read_varint(field_type) != 0;
            break;
        case 6:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Parameter& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.type); });
    if (value.default_value.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.default_value); });
    }
    writer.write_varint(4, static_cast<std::uint64_t>(value.variadic));
    writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, value.range); });
}

Parameter decode_Parameter_from(wire::Reader reader) {
    Parameter value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 3:
            value.default_value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 4:
            value.variadic = reader.read_varint(field_type) != 0;
            break;
        case 5:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const FieldDecl& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.type); });
    if (value.value.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.value); });
    }
    for (const auto& item : value.attributes) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (!value.documentation.empty()) {
        writer.write_string(5, value.documentation);
    }
    writer.write_varint(6, static_cast<std::uint64_t>(value.visibility));
    writer.write_message(7, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(8, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
}

FieldDecl decode_FieldDecl_from(wire::Reader reader) {
    FieldDecl value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 3:
            value.value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 4:
            value.attributes.push_back(decode_Attribute_from(reader.read_message(field_type)));
            break;
        case 5:
            value.documentation = reader.read_string(field_type);
            break;
        case 6:
            value.visibility = static_cast<Visibility>(reader.read_varint(field_type));
            break;
        case 7:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 8:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const FunctionDecl& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    for (const auto& item : value.generic_parameters) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.parameters) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (value.return_type.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.return_type); });
    }
    for (const auto& item : value.body) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.attributes) {
        writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (!value.documentation.empty()) {
        writer.write_string(7, value.documentation);
    }
    writer.write_varint(8, static_cast<std::uint64_t>(value.visibility));
    writer.write_varint(9, static_cast<std::uint64_t>(value.is_static));
    writer.write_varint(10, static_cast<std::uint64_t>(value.is_abstract));
    writer.write_varint(11, static_cast<std::uint64_t>(value.is_virtual));
    writer.write_message(12, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(13, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
}

FunctionDecl decode_FunctionDecl_from(wire::Reader reader) {
    FunctionDecl value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.generic_parameters.push_back(decode_GenericParameter_from(reader.read_message(field_type)));
            break;
        case 3:
            value.parameters.push_back(decode_Parameter_from(reader.read_message(field_type)));
            break;
        case 4:
            value.return_type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 5:
            value.body.push_back(decode_Statement_from(reader.read_message(field_type)));
            break;
        case 6:
            value.attributes.push_back(decode_Attribute_from(reader.read_message(field_type)));
            break;
        case 7:
            value.documentation = reader.read_string(field_type);
            break;
        case 8:
            value.visibility = static_cast<Visibility>(reader.read_varint(field_type));
            break;
        case 9:
            value.is_static = reader.read_varint(field_type) != 0;
            break;
        case 10:
            value.is_abstract = reader.read_varint(field_type) != 0;
            break;
        case 11:
            value.is_virtual = reader.read_varint(field_type) != 0;
            break;
        case 12:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 13:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const EnumVariant& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    for (const auto& item : value.fields) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (value.value.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.value); });
    }
    for (const auto& item : value.attributes) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, value.range); });
}

EnumVariant decode_EnumVariant_from(wire::Reader reader) {
    EnumVariant value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.fields.push_back(decode_FieldDecl_from(reader.read_message(field_type)));
            break;
        case 3:
            value.value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 4:
            value.attributes.push_back(decode_Attribute_from(reader.read_message(field_type)));
            break;
        case 5:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const EnumDecl& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    for (const auto& item : value.generic_parameters) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (value.underlying_type.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.underlying_type); });
    }
    for (const auto& item : value.variants) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.attributes) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (!value.documentation.empty()) {
        writer.write_string(6, value.documentation);
    }
    writer.write_varint(7, static_cast<std::uint64_t>(value.visibility));
    writer.write_message(8, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(9, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
}

EnumDecl decode_EnumDecl_from(wire::Reader reader) {
    EnumDecl value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.generic_parameters.push_back(decode_GenericParameter_from(reader.read_message(field_type)));
            break;
        case 3:
            value.underlying_type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 4:
            value.variants.push_back(decode_EnumVariant_from(reader.read_message(field_type)));
            break;
        case 5:
            value.attributes.push_back(decode_Attribute_from(reader.read_message(field_type)));
            break;
        case 6:
            value.documentation = reader.read_string(field_type);
            break;
        case 7:
            value.visibility = static_cast<Visibility>(reader.read_varint(field_type));
            break;
        case 8:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 9:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const ConstantDecl& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.type); });
    writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, value.value); });
    for (const auto& item : value.attributes) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (!value.documentation.empty()) {
        writer.write_string(5, value.documentation);
    }
    writer.write_varint(6, static_cast<std::uint64_t>(value.visibility));
    writer.write_message(7, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(8, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
}

ConstantDecl decode_ConstantDecl_from(wire::Reader reader) {
    ConstantDecl value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.type = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 3:
            value.value = decode_Expression_from(reader.read_message(field_type));
            break;
        case 4:
            value.attributes.push_back(decode_Attribute_from(reader.read_message(field_type)));
            break;
        case 5:
            value.documentation = reader.read_string(field_type);
            break;
        case 6:
            value.visibility = static_cast<Visibility>(reader.read_varint(field_type));
            break;
        case 7:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 8:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const ClassDecl& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    for (const auto& item : value.generic_parameters) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.bases) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.fields) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.methods) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.attributes) {
        writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    if (!value.documentation.empty()) {
        writer.write_string(7, value.documentation);
    }
    writer.write_varint(8, static_cast<std::uint64_t>(value.visibility));
    writer.write_message(9, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (value.identity.has_value()) {
        writer.write_message(10, [&](wire::Writer& nested) { encode_into(nested, *value.identity); });
    }
    for (const auto& item : value.constants) {
        writer.write_message(11, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.static_fields) {
        writer.write_message(12, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

ClassDecl decode_ClassDecl_from(wire::Reader reader) {
    ClassDecl value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.generic_parameters.push_back(decode_GenericParameter_from(reader.read_message(field_type)));
            break;
        case 3:
            value.bases.push_back(decode_TypeRef_from(reader.read_message(field_type)));
            break;
        case 4:
            value.fields.push_back(decode_FieldDecl_from(reader.read_message(field_type)));
            break;
        case 5:
            value.methods.push_back(decode_FunctionDecl_from(reader.read_message(field_type)));
            break;
        case 6:
            value.attributes.push_back(decode_Attribute_from(reader.read_message(field_type)));
            break;
        case 7:
            value.documentation = reader.read_string(field_type);
            break;
        case 8:
            value.visibility = static_cast<Visibility>(reader.read_varint(field_type));
            break;
        case 9:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 10:
            value.identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        case 11:
            value.constants.push_back(decode_ConstantDecl_from(reader.read_message(field_type)));
            break;
        case 12:
            value.static_fields.push_back(decode_ConstantDecl_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const ImplementationDecl& value) {
    writer.write_message(1, [&](wire::Writer& nested) { encode_into(nested, value.contract); });
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.target); });
    for (const auto& item : value.methods) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, value.range); });
}

ImplementationDecl decode_ImplementationDecl_from(wire::Reader reader) {
    ImplementationDecl value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.contract = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 2:
            value.target = decode_TypeRef_from(reader.read_message(field_type));
            break;
        case 3:
            value.methods.push_back(decode_FunctionDecl_from(reader.read_message(field_type)));
            break;
        case 4:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Declaration& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.kind));
    if (value.class_decl.has_value()) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, *value.class_decl); });
    }
    if (value.enum_decl.has_value()) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, *value.enum_decl); });
    }
    if (value.function_decl.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.function_decl); });
    }
    if (value.field_decl.has_value()) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, *value.field_decl); });
    }
    if (value.constant_decl.has_value()) {
        writer.write_message(6, [&](wire::Writer& nested) { encode_into(nested, *value.constant_decl); });
    }
    if (value.implementation_decl.has_value()) {
        writer.write_message(7, [&](wire::Writer& nested) { encode_into(nested, *value.implementation_decl); });
    }
}

Declaration decode_Declaration_from(wire::Reader reader) {
    Declaration value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.kind = static_cast<DeclarationKind>(reader.read_varint(field_type));
            break;
        case 2:
            value.class_decl = decode_ClassDecl_from(reader.read_message(field_type));
            break;
        case 3:
            value.enum_decl = decode_EnumDecl_from(reader.read_message(field_type));
            break;
        case 4:
            value.function_decl = decode_FunctionDecl_from(reader.read_message(field_type));
            break;
        case 5:
            value.field_decl = decode_FieldDecl_from(reader.read_message(field_type));
            break;
        case 6:
            value.constant_decl = decode_ConstantDecl_from(reader.read_message(field_type));
            break;
        case 7:
            value.implementation_decl = decode_ImplementationDecl_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const SourceOrigin& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.kind));
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    if (!value.macro_name.empty()) {
        writer.write_string(3, value.macro_name);
    }
    if (value.macro_identity.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.macro_identity); });
    }
    if (value.parent.has_value()) {
        writer.write_varint(5, static_cast<std::uint64_t>(*value.parent));
    }
}

SourceOrigin decode_SourceOrigin_from(wire::Reader reader) {
    SourceOrigin value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.kind = static_cast<OriginKind>(reader.read_varint(field_type));
            break;
        case 2:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 3:
            value.macro_name = reader.read_string(field_type);
            break;
        case 4:
            value.macro_identity = decode_SymbolIdentity_from(reader.read_message(field_type));
            break;
        case 5:
            value.parent = reader.read_varint(field_type);
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const GeneratedDeclaration& value) {
    writer.write_message(1, [&](wire::Writer& nested) { encode_into(nested, value.declaration); });
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.origin); });
}

GeneratedDeclaration decode_GeneratedDeclaration_from(wire::Reader reader) {
    GeneratedDeclaration value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.declaration = decode_Declaration_from(reader.read_message(field_type));
            break;
        case 2:
            value.origin = decode_SourceOrigin_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Diagnostic& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.severity));
    if (!value.code.empty()) {
        writer.write_string(2, value.code);
    }
    if (!value.message.empty()) {
        writer.write_string(3, value.message);
    }
    writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, value.range); });
    for (const auto& item : value.notes) {
        writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

Diagnostic decode_Diagnostic_from(wire::Reader reader) {
    Diagnostic value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.severity = static_cast<DiagnosticSeverity>(reader.read_varint(field_type));
            break;
        case 2:
            value.code = reader.read_string(field_type);
            break;
        case 3:
            value.message = reader.read_string(field_type);
            break;
        case 4:
            value.range = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 5:
            value.notes.push_back(decode_Diagnostic_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Expansion& value) {
    for (const auto& item : value.members) {
        writer.write_message(1, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.siblings) {
        writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.implementations) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.diagnostics) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

Expansion decode_Expansion_from(wire::Reader reader) {
    Expansion value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.members.push_back(decode_GeneratedDeclaration_from(reader.read_message(field_type)));
            break;
        case 2:
            value.siblings.push_back(decode_GeneratedDeclaration_from(reader.read_message(field_type)));
            break;
        case 3:
            value.implementations.push_back(decode_GeneratedDeclaration_from(reader.read_message(field_type)));
            break;
        case 4:
            value.diagnostics.push_back(decode_Diagnostic_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Capability& value) {
    writer.write_varint(1, static_cast<std::uint64_t>(value.kind));
    for (const auto& item : value.values) {
        writer.write_string(2, item);
    }
}

Capability decode_Capability_from(wire::Reader reader) {
    Capability value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.kind = static_cast<CapabilityKind>(reader.read_varint(field_type));
            break;
        case 2:
            value.values.push_back(reader.read_string(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const MacroDescriptor& value) {
    if (!value.name.empty()) {
        writer.write_string(1, value.name);
    }
    if (!value.entry_point.empty()) {
        writer.write_string(2, value.entry_point);
    }
    writer.write_varint(3, static_cast<std::uint64_t>(value.accepted_kind));
    if (value.attribute_schema.has_value()) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, *value.attribute_schema); });
    }
    writer.write_message(5, [&](wire::Writer& nested) { encode_into(nested, value.definition); });
}

MacroDescriptor decode_MacroDescriptor_from(wire::Reader reader) {
    MacroDescriptor value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.name = reader.read_string(field_type);
            break;
        case 2:
            value.entry_point = reader.read_string(field_type);
            break;
        case 3:
            value.accepted_kind = static_cast<DeclarationKind>(reader.read_varint(field_type));
            break;
        case 4:
            value.attribute_schema = decode_ClassDecl_from(reader.read_message(field_type));
            break;
        case 5:
            value.definition = decode_SourceRange_from(reader.read_message(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const MacroCatalog& value) {
    if (!value.package.empty()) {
        writer.write_string(1, value.package);
    }
    if (!value.binary_identity.empty()) {
        writer.write_string(2, value.binary_identity);
    }
    for (const auto& item : value.macros) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
    for (const auto& item : value.capabilities) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

MacroCatalog decode_MacroCatalog_from(wire::Reader reader) {
    MacroCatalog value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.package = reader.read_string(field_type);
            break;
        case 2:
            value.binary_identity = reader.read_string(field_type);
            break;
        case 3:
            value.macros.push_back(decode_MacroDescriptor_from(reader.read_message(field_type)));
            break;
        case 4:
            value.capabilities.push_back(decode_Capability_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const Hello& value) {
    if (!value.compiler_version.empty()) {
        writer.write_string(1, value.compiler_version);
    }
    writer.write_varint(2, static_cast<std::uint64_t>(value.protocol_version));
    writer.write_varint(3, static_cast<std::uint64_t>(value.schema_version));
    writer.write_varint(4, static_cast<std::uint64_t>(value.max_frame_bytes));
}

Hello decode_Hello_from(wire::Reader reader) {
    Hello value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.compiler_version = reader.read_string(field_type);
            break;
        case 2:
            value.protocol_version = reader.read_u32(field_type);
            break;
        case 3:
            value.schema_version = reader.read_u32(field_type);
            break;
        case 4:
            value.max_frame_bytes = reader.read_varint(field_type);
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const HelloAck& value) {
    if (!value.worker_version.empty()) {
        writer.write_string(1, value.worker_version);
    }
    writer.write_varint(2, static_cast<std::uint64_t>(value.protocol_version));
    writer.write_varint(3, static_cast<std::uint64_t>(value.schema_version));
    writer.write_varint(4, static_cast<std::uint64_t>(value.accepted));
    if (!value.reason.empty()) {
        writer.write_string(5, value.reason);
    }
}

HelloAck decode_HelloAck_from(wire::Reader reader) {
    HelloAck value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.worker_version = reader.read_string(field_type);
            break;
        case 2:
            value.protocol_version = reader.read_u32(field_type);
            break;
        case 3:
            value.schema_version = reader.read_u32(field_type);
            break;
        case 4:
            value.accepted = reader.read_varint(field_type) != 0;
            break;
        case 5:
            value.reason = reader.read_string(field_type);
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const ExpansionRequest& value) {
    if (!value.macro_name.empty()) {
        writer.write_string(1, value.macro_name);
    }
    writer.write_message(2, [&](wire::Writer& nested) { encode_into(nested, value.declaration); });
    writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, value.invocation); });
    for (const auto& item : value.compile_values) {
        writer.write_message(4, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

ExpansionRequest decode_ExpansionRequest_from(wire::Reader reader) {
    ExpansionRequest value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.macro_name = reader.read_string(field_type);
            break;
        case 2:
            value.declaration = decode_Declaration_from(reader.read_message(field_type));
            break;
        case 3:
            value.invocation = decode_SourceRange_from(reader.read_message(field_type));
            break;
        case 4:
            value.compile_values.push_back(decode_AttributeArgument_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const ExpansionResponse& value) {
    writer.write_message(1, [&](wire::Writer& nested) { encode_into(nested, value.expansion); });
    writer.write_varint(2, static_cast<std::uint64_t>(value.cacheable));
    for (const auto& item : value.external_input_hashes) {
        writer.write_string(3, item);
    }
}

ExpansionResponse decode_ExpansionResponse_from(wire::Reader reader) {
    ExpansionResponse value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.expansion = decode_Expansion_from(reader.read_message(field_type));
            break;
        case 2:
            value.cacheable = reader.read_varint(field_type) != 0;
            break;
        case 3:
            value.external_input_hashes.push_back(reader.read_string(field_type));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

void encode_into(wire::Writer& writer, const WorkerError& value) {
    if (!value.code.empty()) {
        writer.write_string(1, value.code);
    }
    if (!value.message.empty()) {
        writer.write_string(2, value.message);
    }
    for (const auto& item : value.diagnostics) {
        writer.write_message(3, [&](wire::Writer& nested) { encode_into(nested, item); });
    }
}

WorkerError decode_WorkerError_from(wire::Reader reader) {
    WorkerError value;
    std::uint32_t tag = 0;
    wire::FieldType field_type = wire::FieldType::Varint;
    while (reader.next(tag, field_type)) {
        switch (tag) {
        case 1:
            value.code = reader.read_string(field_type);
            break;
        case 2:
            value.message = reader.read_string(field_type);
            break;
        case 3:
            value.diagnostics.push_back(decode_Diagnostic_from(reader.read_message(field_type)));
            break;
        default:
            reader.skip(field_type);
            break;
        }
    }
    return value;
}

} // namespace

std::vector<std::uint8_t> encode(const SourcePosition& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

SourcePosition decode_SourcePosition(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_SourcePosition_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const SourceRange& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

SourceRange decode_SourceRange(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_SourceRange_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const SymbolIdentity& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

SymbolIdentity decode_SymbolIdentity(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_SymbolIdentity_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const TypeRef& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

TypeRef decode_TypeRef(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_TypeRef_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Expression& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Expression decode_Expression(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Expression_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Statement& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Statement decode_Statement(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Statement_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const AttributeArgument& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

AttributeArgument decode_AttributeArgument(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_AttributeArgument_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Attribute& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Attribute decode_Attribute(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Attribute_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const GenericParameter& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

GenericParameter decode_GenericParameter(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_GenericParameter_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Parameter& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Parameter decode_Parameter(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Parameter_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const FieldDecl& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

FieldDecl decode_FieldDecl(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_FieldDecl_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const FunctionDecl& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

FunctionDecl decode_FunctionDecl(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_FunctionDecl_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const EnumVariant& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

EnumVariant decode_EnumVariant(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_EnumVariant_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const EnumDecl& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

EnumDecl decode_EnumDecl(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_EnumDecl_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const ConstantDecl& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

ConstantDecl decode_ConstantDecl(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_ConstantDecl_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const ClassDecl& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

ClassDecl decode_ClassDecl(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_ClassDecl_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const ImplementationDecl& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

ImplementationDecl decode_ImplementationDecl(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_ImplementationDecl_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Declaration& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Declaration decode_Declaration(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Declaration_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const SourceOrigin& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

SourceOrigin decode_SourceOrigin(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_SourceOrigin_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const GeneratedDeclaration& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

GeneratedDeclaration decode_GeneratedDeclaration(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_GeneratedDeclaration_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Diagnostic& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Diagnostic decode_Diagnostic(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Diagnostic_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Expansion& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Expansion decode_Expansion(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Expansion_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Capability& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Capability decode_Capability(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Capability_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const MacroDescriptor& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

MacroDescriptor decode_MacroDescriptor(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_MacroDescriptor_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const MacroCatalog& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

MacroCatalog decode_MacroCatalog(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_MacroCatalog_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const Hello& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

Hello decode_Hello(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_Hello_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const HelloAck& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

HelloAck decode_HelloAck(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_HelloAck_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const ExpansionRequest& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

ExpansionRequest decode_ExpansionRequest(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_ExpansionRequest_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const ExpansionResponse& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

ExpansionResponse decode_ExpansionResponse(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_ExpansionResponse_from(wire::Reader::root(bytes, limits));
}

std::vector<std::uint8_t> encode(const WorkerError& value) {
    wire::Writer writer;
    encode_into(writer, value);
    return writer.take();
}

WorkerError decode_WorkerError(std::span<const std::uint8_t> bytes,
                       const wire::DecodeLimits& limits) {
    return decode_WorkerError_from(wire::Reader::root(bytes, limits));
}

} // namespace dudu::macro::protocol
