// Generated by scripts/generate_macro_ast.py. Do not edit.
#pragma once

#include "dudu/macro/macro_protocol_generated.hpp"
#include "dudu/ast.hpp"

namespace dudu::macro::sdk_bridge {

inline DuduDuduAstVisibility from_protocol(protocol::Visibility input) {
    return static_cast<DuduDuduAstVisibility>(input);
}
inline protocol::Visibility to_protocol(DuduDuduAstVisibility input) {
    return static_cast<protocol::Visibility>(input);
}

inline DuduDuduAstDeclarationKind from_protocol(protocol::DeclarationKind input) {
    return static_cast<DuduDuduAstDeclarationKind>(input);
}
inline protocol::DeclarationKind to_protocol(DuduDuduAstDeclarationKind input) {
    return static_cast<protocol::DeclarationKind>(input);
}

inline DuduDuduAstTypeKind from_protocol(protocol::TypeKind input) {
    return static_cast<DuduDuduAstTypeKind>(input);
}
inline protocol::TypeKind to_protocol(DuduDuduAstTypeKind input) {
    return static_cast<protocol::TypeKind>(input);
}

inline DuduDuduAstExpressionKind from_protocol(protocol::ExpressionKind input) {
    return static_cast<DuduDuduAstExpressionKind>(input);
}
inline protocol::ExpressionKind to_protocol(DuduDuduAstExpressionKind input) {
    return static_cast<protocol::ExpressionKind>(input);
}

inline DuduDuduAstStatementKind from_protocol(protocol::StatementKind input) {
    return static_cast<DuduDuduAstStatementKind>(input);
}
inline protocol::StatementKind to_protocol(DuduDuduAstStatementKind input) {
    return static_cast<protocol::StatementKind>(input);
}

inline DuduDuduAstDiagnosticSeverity from_protocol(protocol::DiagnosticSeverity input) {
    return static_cast<DuduDuduAstDiagnosticSeverity>(input);
}
inline protocol::DiagnosticSeverity to_protocol(DuduDuduAstDiagnosticSeverity input) {
    return static_cast<protocol::DiagnosticSeverity>(input);
}

inline DuduDuduAstOriginKind from_protocol(protocol::OriginKind input) {
    return static_cast<DuduDuduAstOriginKind>(input);
}
inline protocol::OriginKind to_protocol(DuduDuduAstOriginKind input) {
    return static_cast<protocol::OriginKind>(input);
}

inline DuduDuduAstCapabilityKind from_protocol(protocol::CapabilityKind input) {
    return static_cast<DuduDuduAstCapabilityKind>(input);
}
inline protocol::CapabilityKind to_protocol(DuduDuduAstCapabilityKind input) {
    return static_cast<protocol::CapabilityKind>(input);
}

inline DuduDuduAstMessageKind from_protocol(protocol::MessageKind input) {
    return static_cast<DuduDuduAstMessageKind>(input);
}
inline protocol::MessageKind to_protocol(DuduDuduAstMessageKind input) {
    return static_cast<protocol::MessageKind>(input);
}

DuduDuduAstSourcePosition from_protocol(const protocol::SourcePosition& input);
protocol::SourcePosition to_protocol(const DuduDuduAstSourcePosition& input);
DuduDuduAstSourceRange from_protocol(const protocol::SourceRange& input);
protocol::SourceRange to_protocol(const DuduDuduAstSourceRange& input);
DuduDuduAstSymbolIdentity from_protocol(const protocol::SymbolIdentity& input);
protocol::SymbolIdentity to_protocol(const DuduDuduAstSymbolIdentity& input);
DuduDuduAstTypeRef from_protocol(const protocol::TypeRef& input);
protocol::TypeRef to_protocol(const DuduDuduAstTypeRef& input);
DuduDuduAstExpression from_protocol(const protocol::Expression& input);
protocol::Expression to_protocol(const DuduDuduAstExpression& input);
DuduDuduAstStatement from_protocol(const protocol::Statement& input);
protocol::Statement to_protocol(const DuduDuduAstStatement& input);
DuduDuduAstAttributeArgument from_protocol(const protocol::AttributeArgument& input);
protocol::AttributeArgument to_protocol(const DuduDuduAstAttributeArgument& input);
DuduDuduAstAttribute from_protocol(const protocol::Attribute& input);
protocol::Attribute to_protocol(const DuduDuduAstAttribute& input);
DuduDuduAstGenericParameter from_protocol(const protocol::GenericParameter& input);
protocol::GenericParameter to_protocol(const DuduDuduAstGenericParameter& input);
DuduDuduAstParameter from_protocol(const protocol::Parameter& input);
protocol::Parameter to_protocol(const DuduDuduAstParameter& input);
DuduDuduAstFieldDecl from_protocol(const protocol::FieldDecl& input);
protocol::FieldDecl to_protocol(const DuduDuduAstFieldDecl& input);
DuduDuduAstFunctionDecl from_protocol(const protocol::FunctionDecl& input);
protocol::FunctionDecl to_protocol(const DuduDuduAstFunctionDecl& input);
DuduDuduAstEnumVariant from_protocol(const protocol::EnumVariant& input);
protocol::EnumVariant to_protocol(const DuduDuduAstEnumVariant& input);
DuduDuduAstEnumDecl from_protocol(const protocol::EnumDecl& input);
protocol::EnumDecl to_protocol(const DuduDuduAstEnumDecl& input);
DuduDuduAstConstantDecl from_protocol(const protocol::ConstantDecl& input);
protocol::ConstantDecl to_protocol(const DuduDuduAstConstantDecl& input);
DuduDuduAstClassDecl from_protocol(const protocol::ClassDecl& input);
protocol::ClassDecl to_protocol(const DuduDuduAstClassDecl& input);
DuduDuduAstImplementationDecl from_protocol(const protocol::ImplementationDecl& input);
protocol::ImplementationDecl to_protocol(const DuduDuduAstImplementationDecl& input);
DuduDuduAstDeclaration from_protocol(const protocol::Declaration& input);
protocol::Declaration to_protocol(const DuduDuduAstDeclaration& input);
DuduDuduAstSourceOrigin from_protocol(const protocol::SourceOrigin& input);
protocol::SourceOrigin to_protocol(const DuduDuduAstSourceOrigin& input);
DuduDuduAstGeneratedDeclaration from_protocol(const protocol::GeneratedDeclaration& input);
protocol::GeneratedDeclaration to_protocol(const DuduDuduAstGeneratedDeclaration& input);
DuduDuduAstDiagnostic from_protocol(const protocol::Diagnostic& input);
protocol::Diagnostic to_protocol(const DuduDuduAstDiagnostic& input);
DuduDuduAstExpansion from_protocol(const protocol::Expansion& input);
protocol::Expansion to_protocol(const DuduDuduAstExpansion& input);
DuduDuduAstCapability from_protocol(const protocol::Capability& input);
protocol::Capability to_protocol(const DuduDuduAstCapability& input);
DuduDuduAstMacroDescriptor from_protocol(const protocol::MacroDescriptor& input);
protocol::MacroDescriptor to_protocol(const DuduDuduAstMacroDescriptor& input);
DuduDuduAstMacroCatalog from_protocol(const protocol::MacroCatalog& input);
protocol::MacroCatalog to_protocol(const DuduDuduAstMacroCatalog& input);
DuduDuduAstHello from_protocol(const protocol::Hello& input);
protocol::Hello to_protocol(const DuduDuduAstHello& input);
DuduDuduAstHelloAck from_protocol(const protocol::HelloAck& input);
protocol::HelloAck to_protocol(const DuduDuduAstHelloAck& input);
DuduDuduAstExpansionRequest from_protocol(const protocol::ExpansionRequest& input);
protocol::ExpansionRequest to_protocol(const DuduDuduAstExpansionRequest& input);
DuduDuduAstExpansionResponse from_protocol(const protocol::ExpansionResponse& input);
protocol::ExpansionResponse to_protocol(const DuduDuduAstExpansionResponse& input);
DuduDuduAstWorkerError from_protocol(const protocol::WorkerError& input);
protocol::WorkerError to_protocol(const DuduDuduAstWorkerError& input);

inline DuduDuduAstSourcePosition from_protocol(const protocol::SourcePosition& input) {
    DuduDuduAstSourcePosition out;
    out.line = input.line;
    out.column = input.column;
    out.offset = input.offset;
    return out;
}

inline protocol::SourcePosition to_protocol(const DuduDuduAstSourcePosition& input) {
    protocol::SourcePosition out;
    out.line = input.line;
    out.column = input.column;
    out.offset = input.offset;
    return out;
}

inline DuduDuduAstSourceRange from_protocol(const protocol::SourceRange& input) {
    DuduDuduAstSourceRange out;
    out.file = input.file;
    out.start = from_protocol(input.start);
    out.end = from_protocol(input.end);
    return out;
}

inline protocol::SourceRange to_protocol(const DuduDuduAstSourceRange& input) {
    protocol::SourceRange out;
    out.file = input.file;
    out.start = to_protocol(input.start);
    out.end = to_protocol(input.end);
    return out;
}

inline DuduDuduAstSymbolIdentity from_protocol(const protocol::SymbolIdentity& input) {
    DuduDuduAstSymbolIdentity out;
    out.package = input.package;
    out.module = input.module;
    out.path = input.path;
    out.native_identity = input.native_identity;
    return out;
}

inline protocol::SymbolIdentity to_protocol(const DuduDuduAstSymbolIdentity& input) {
    protocol::SymbolIdentity out;
    out.package = input.package;
    out.module = input.module;
    out.path = input.path;
    out.native_identity = input.native_identity;
    return out;
}

inline DuduDuduAstTypeRef from_protocol(const protocol::TypeRef& input) {
    DuduDuduAstTypeRef out;
    out.kind = static_cast<DuduDuduAstTypeKind>(input.kind);
    out.name = input.name;
    out.value = input.value;
    out.children.reserve(input.children.size());
    for (const auto& item : input.children) {
        out.children.push_back(from_protocol(item));
    }
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    return out;
}

inline protocol::TypeRef to_protocol(const DuduDuduAstTypeRef& input) {
    protocol::TypeRef out;
    out.kind = static_cast<protocol::TypeKind>(input.kind);
    out.name = input.name;
    out.value = input.value;
    out.children.reserve(input.children.size());
    for (const auto& item : input.children) {
        out.children.push_back(to_protocol(item));
    }
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    return out;
}

inline DuduDuduAstExpression from_protocol(const protocol::Expression& input) {
    DuduDuduAstExpression out;
    out.kind = static_cast<DuduDuduAstExpressionKind>(input.kind);
    out.name = input.name;
    out.value = input.value;
    out.operator_name = input.operator_name;
    out.children.reserve(input.children.size());
    for (const auto& item : input.children) {
        out.children.push_back(from_protocol(item));
    }
    out.type_arguments.reserve(input.type_arguments.size());
    for (const auto& item : input.type_arguments) {
        out.type_arguments.push_back(from_protocol(item));
    }
    out.range = from_protocol(input.range);
    if (input.resolved_type.has_value()) {
        out.resolved_type = from_protocol(*input.resolved_type);
    }
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    out.callee.reserve(input.callee.size());
    for (const auto& item : input.callee) {
        out.callee.push_back(from_protocol(item));
    }
    out.template_arguments.reserve(input.template_arguments.size());
    for (const auto& item : input.template_arguments) {
        out.template_arguments.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::Expression to_protocol(const DuduDuduAstExpression& input) {
    protocol::Expression out;
    out.kind = static_cast<protocol::ExpressionKind>(input.kind);
    out.name = input.name;
    out.value = input.value;
    out.operator_name = input.operator_name;
    out.children.reserve(input.children.size());
    for (const auto& item : input.children) {
        out.children.push_back(to_protocol(item));
    }
    out.type_arguments.reserve(input.type_arguments.size());
    for (const auto& item : input.type_arguments) {
        out.type_arguments.push_back(to_protocol(item));
    }
    out.range = to_protocol(input.range);
    if (input.resolved_type.has_value()) {
        out.resolved_type = to_protocol(*input.resolved_type);
    }
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    out.callee.reserve(input.callee.size());
    for (const auto& item : input.callee) {
        out.callee.push_back(to_protocol(item));
    }
    out.template_arguments.reserve(input.template_arguments.size());
    for (const auto& item : input.template_arguments) {
        out.template_arguments.push_back(to_protocol(item));
    }
    return out;
}

inline DuduDuduAstStatement from_protocol(const protocol::Statement& input) {
    DuduDuduAstStatement out;
    out.kind = static_cast<DuduDuduAstStatementKind>(input.kind);
    out.name = input.name;
    if (input.type.has_value()) {
        out.type = from_protocol(*input.type);
    }
    if (input.expression.has_value()) {
        out.expression = from_protocol(*input.expression);
    }
    if (input.value.has_value()) {
        out.value = from_protocol(*input.value);
    }
    if (input.target.has_value()) {
        out.target = from_protocol(*input.target);
    }
    if (input.condition.has_value()) {
        out.condition = from_protocol(*input.condition);
    }
    out.children.reserve(input.children.size());
    for (const auto& item : input.children) {
        out.children.push_back(from_protocol(item));
    }
    out.range = from_protocol(input.range);
    if (input.message.has_value()) {
        out.message = from_protocol(*input.message);
    }
    if (input.iterable.has_value()) {
        out.iterable = from_protocol(*input.iterable);
    }
    if (input.pattern.has_value()) {
        out.pattern = from_protocol(*input.pattern);
    }
    if (input.guard.has_value()) {
        out.guard = from_protocol(*input.guard);
    }
    out.operator_name = input.operator_name;
    return out;
}

inline protocol::Statement to_protocol(const DuduDuduAstStatement& input) {
    protocol::Statement out;
    out.kind = static_cast<protocol::StatementKind>(input.kind);
    out.name = input.name;
    if (input.type.has_value()) {
        out.type = to_protocol(*input.type);
    }
    if (input.expression.has_value()) {
        out.expression = to_protocol(*input.expression);
    }
    if (input.value.has_value()) {
        out.value = to_protocol(*input.value);
    }
    if (input.target.has_value()) {
        out.target = to_protocol(*input.target);
    }
    if (input.condition.has_value()) {
        out.condition = to_protocol(*input.condition);
    }
    out.children.reserve(input.children.size());
    for (const auto& item : input.children) {
        out.children.push_back(to_protocol(item));
    }
    out.range = to_protocol(input.range);
    if (input.message.has_value()) {
        out.message = to_protocol(*input.message);
    }
    if (input.iterable.has_value()) {
        out.iterable = to_protocol(*input.iterable);
    }
    if (input.pattern.has_value()) {
        out.pattern = to_protocol(*input.pattern);
    }
    if (input.guard.has_value()) {
        out.guard = to_protocol(*input.guard);
    }
    out.operator_name = input.operator_name;
    return out;
}

inline DuduDuduAstAttributeArgument from_protocol(const protocol::AttributeArgument& input) {
    DuduDuduAstAttributeArgument out;
    out.name = input.name;
    out.value = from_protocol(input.value);
    out.range = from_protocol(input.range);
    return out;
}

inline protocol::AttributeArgument to_protocol(const DuduDuduAstAttributeArgument& input) {
    protocol::AttributeArgument out;
    out.name = input.name;
    out.value = to_protocol(input.value);
    out.range = to_protocol(input.range);
    return out;
}

inline DuduDuduAstAttribute from_protocol(const protocol::Attribute& input) {
    DuduDuduAstAttribute out;
    out.name = input.name;
    out.arguments.reserve(input.arguments.size());
    for (const auto& item : input.arguments) {
        out.arguments.push_back(from_protocol(item));
    }
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    return out;
}

inline protocol::Attribute to_protocol(const DuduDuduAstAttribute& input) {
    protocol::Attribute out;
    out.name = input.name;
    out.arguments.reserve(input.arguments.size());
    for (const auto& item : input.arguments) {
        out.arguments.push_back(to_protocol(item));
    }
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    return out;
}

inline DuduDuduAstGenericParameter from_protocol(const protocol::GenericParameter& input) {
    DuduDuduAstGenericParameter out;
    out.name = input.name;
    if (input.type.has_value()) {
        out.type = from_protocol(*input.type);
    }
    if (input.default_type.has_value()) {
        out.default_type = from_protocol(*input.default_type);
    }
    if (input.default_value.has_value()) {
        out.default_value = from_protocol(*input.default_value);
    }
    out.variadic = input.variadic;
    out.range = from_protocol(input.range);
    return out;
}

inline protocol::GenericParameter to_protocol(const DuduDuduAstGenericParameter& input) {
    protocol::GenericParameter out;
    out.name = input.name;
    if (input.type.has_value()) {
        out.type = to_protocol(*input.type);
    }
    if (input.default_type.has_value()) {
        out.default_type = to_protocol(*input.default_type);
    }
    if (input.default_value.has_value()) {
        out.default_value = to_protocol(*input.default_value);
    }
    out.variadic = input.variadic;
    out.range = to_protocol(input.range);
    return out;
}

inline DuduDuduAstParameter from_protocol(const protocol::Parameter& input) {
    DuduDuduAstParameter out;
    out.name = input.name;
    out.type = from_protocol(input.type);
    if (input.default_value.has_value()) {
        out.default_value = from_protocol(*input.default_value);
    }
    out.variadic = input.variadic;
    out.range = from_protocol(input.range);
    return out;
}

inline protocol::Parameter to_protocol(const DuduDuduAstParameter& input) {
    protocol::Parameter out;
    out.name = input.name;
    out.type = to_protocol(input.type);
    if (input.default_value.has_value()) {
        out.default_value = to_protocol(*input.default_value);
    }
    out.variadic = input.variadic;
    out.range = to_protocol(input.range);
    return out;
}

inline DuduDuduAstFieldDecl from_protocol(const protocol::FieldDecl& input) {
    DuduDuduAstFieldDecl out;
    out.name = input.name;
    out.type = from_protocol(input.type);
    if (input.value.has_value()) {
        out.value = from_protocol(*input.value);
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(from_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<DuduDuduAstVisibility>(input.visibility);
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    return out;
}

inline protocol::FieldDecl to_protocol(const DuduDuduAstFieldDecl& input) {
    protocol::FieldDecl out;
    out.name = input.name;
    out.type = to_protocol(input.type);
    if (input.value.has_value()) {
        out.value = to_protocol(*input.value);
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(to_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<protocol::Visibility>(input.visibility);
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    return out;
}

inline DuduDuduAstFunctionDecl from_protocol(const protocol::FunctionDecl& input) {
    DuduDuduAstFunctionDecl out;
    out.name = input.name;
    out.generic_parameters.reserve(input.generic_parameters.size());
    for (const auto& item : input.generic_parameters) {
        out.generic_parameters.push_back(from_protocol(item));
    }
    out.parameters.reserve(input.parameters.size());
    for (const auto& item : input.parameters) {
        out.parameters.push_back(from_protocol(item));
    }
    if (input.return_type.has_value()) {
        out.return_type = from_protocol(*input.return_type);
    }
    out.body.reserve(input.body.size());
    for (const auto& item : input.body) {
        out.body.push_back(from_protocol(item));
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(from_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<DuduDuduAstVisibility>(input.visibility);
    out.is_static = input.is_static;
    out.is_abstract = input.is_abstract;
    out.is_virtual = input.is_virtual;
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    return out;
}

inline protocol::FunctionDecl to_protocol(const DuduDuduAstFunctionDecl& input) {
    protocol::FunctionDecl out;
    out.name = input.name;
    out.generic_parameters.reserve(input.generic_parameters.size());
    for (const auto& item : input.generic_parameters) {
        out.generic_parameters.push_back(to_protocol(item));
    }
    out.parameters.reserve(input.parameters.size());
    for (const auto& item : input.parameters) {
        out.parameters.push_back(to_protocol(item));
    }
    if (input.return_type.has_value()) {
        out.return_type = to_protocol(*input.return_type);
    }
    out.body.reserve(input.body.size());
    for (const auto& item : input.body) {
        out.body.push_back(to_protocol(item));
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(to_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<protocol::Visibility>(input.visibility);
    out.is_static = input.is_static;
    out.is_abstract = input.is_abstract;
    out.is_virtual = input.is_virtual;
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    return out;
}

inline DuduDuduAstEnumVariant from_protocol(const protocol::EnumVariant& input) {
    DuduDuduAstEnumVariant out;
    out.name = input.name;
    out.fields.reserve(input.fields.size());
    for (const auto& item : input.fields) {
        out.fields.push_back(from_protocol(item));
    }
    if (input.value.has_value()) {
        out.value = from_protocol(*input.value);
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(from_protocol(item));
    }
    out.range = from_protocol(input.range);
    return out;
}

inline protocol::EnumVariant to_protocol(const DuduDuduAstEnumVariant& input) {
    protocol::EnumVariant out;
    out.name = input.name;
    out.fields.reserve(input.fields.size());
    for (const auto& item : input.fields) {
        out.fields.push_back(to_protocol(item));
    }
    if (input.value.has_value()) {
        out.value = to_protocol(*input.value);
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(to_protocol(item));
    }
    out.range = to_protocol(input.range);
    return out;
}

inline DuduDuduAstEnumDecl from_protocol(const protocol::EnumDecl& input) {
    DuduDuduAstEnumDecl out;
    out.name = input.name;
    out.generic_parameters.reserve(input.generic_parameters.size());
    for (const auto& item : input.generic_parameters) {
        out.generic_parameters.push_back(from_protocol(item));
    }
    if (input.underlying_type.has_value()) {
        out.underlying_type = from_protocol(*input.underlying_type);
    }
    out.variants.reserve(input.variants.size());
    for (const auto& item : input.variants) {
        out.variants.push_back(from_protocol(item));
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(from_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<DuduDuduAstVisibility>(input.visibility);
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    return out;
}

inline protocol::EnumDecl to_protocol(const DuduDuduAstEnumDecl& input) {
    protocol::EnumDecl out;
    out.name = input.name;
    out.generic_parameters.reserve(input.generic_parameters.size());
    for (const auto& item : input.generic_parameters) {
        out.generic_parameters.push_back(to_protocol(item));
    }
    if (input.underlying_type.has_value()) {
        out.underlying_type = to_protocol(*input.underlying_type);
    }
    out.variants.reserve(input.variants.size());
    for (const auto& item : input.variants) {
        out.variants.push_back(to_protocol(item));
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(to_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<protocol::Visibility>(input.visibility);
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    return out;
}

inline DuduDuduAstConstantDecl from_protocol(const protocol::ConstantDecl& input) {
    DuduDuduAstConstantDecl out;
    out.name = input.name;
    out.type = from_protocol(input.type);
    out.value = from_protocol(input.value);
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(from_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<DuduDuduAstVisibility>(input.visibility);
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    return out;
}

inline protocol::ConstantDecl to_protocol(const DuduDuduAstConstantDecl& input) {
    protocol::ConstantDecl out;
    out.name = input.name;
    out.type = to_protocol(input.type);
    out.value = to_protocol(input.value);
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(to_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<protocol::Visibility>(input.visibility);
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    return out;
}

inline DuduDuduAstClassDecl from_protocol(const protocol::ClassDecl& input) {
    DuduDuduAstClassDecl out;
    out.name = input.name;
    out.generic_parameters.reserve(input.generic_parameters.size());
    for (const auto& item : input.generic_parameters) {
        out.generic_parameters.push_back(from_protocol(item));
    }
    out.bases.reserve(input.bases.size());
    for (const auto& item : input.bases) {
        out.bases.push_back(from_protocol(item));
    }
    out.fields.reserve(input.fields.size());
    for (const auto& item : input.fields) {
        out.fields.push_back(from_protocol(item));
    }
    out.methods.reserve(input.methods.size());
    for (const auto& item : input.methods) {
        out.methods.push_back(from_protocol(item));
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(from_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<DuduDuduAstVisibility>(input.visibility);
    out.range = from_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = from_protocol(*input.identity);
    }
    out.constants.reserve(input.constants.size());
    for (const auto& item : input.constants) {
        out.constants.push_back(from_protocol(item));
    }
    out.static_fields.reserve(input.static_fields.size());
    for (const auto& item : input.static_fields) {
        out.static_fields.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::ClassDecl to_protocol(const DuduDuduAstClassDecl& input) {
    protocol::ClassDecl out;
    out.name = input.name;
    out.generic_parameters.reserve(input.generic_parameters.size());
    for (const auto& item : input.generic_parameters) {
        out.generic_parameters.push_back(to_protocol(item));
    }
    out.bases.reserve(input.bases.size());
    for (const auto& item : input.bases) {
        out.bases.push_back(to_protocol(item));
    }
    out.fields.reserve(input.fields.size());
    for (const auto& item : input.fields) {
        out.fields.push_back(to_protocol(item));
    }
    out.methods.reserve(input.methods.size());
    for (const auto& item : input.methods) {
        out.methods.push_back(to_protocol(item));
    }
    out.attributes.reserve(input.attributes.size());
    for (const auto& item : input.attributes) {
        out.attributes.push_back(to_protocol(item));
    }
    out.documentation = input.documentation;
    out.visibility = static_cast<protocol::Visibility>(input.visibility);
    out.range = to_protocol(input.range);
    if (input.identity.has_value()) {
        out.identity = to_protocol(*input.identity);
    }
    out.constants.reserve(input.constants.size());
    for (const auto& item : input.constants) {
        out.constants.push_back(to_protocol(item));
    }
    out.static_fields.reserve(input.static_fields.size());
    for (const auto& item : input.static_fields) {
        out.static_fields.push_back(to_protocol(item));
    }
    return out;
}

inline DuduDuduAstImplementationDecl from_protocol(const protocol::ImplementationDecl& input) {
    DuduDuduAstImplementationDecl out;
    out.contract = from_protocol(input.contract);
    out.target = from_protocol(input.target);
    out.methods.reserve(input.methods.size());
    for (const auto& item : input.methods) {
        out.methods.push_back(from_protocol(item));
    }
    out.range = from_protocol(input.range);
    return out;
}

inline protocol::ImplementationDecl to_protocol(const DuduDuduAstImplementationDecl& input) {
    protocol::ImplementationDecl out;
    out.contract = to_protocol(input.contract);
    out.target = to_protocol(input.target);
    out.methods.reserve(input.methods.size());
    for (const auto& item : input.methods) {
        out.methods.push_back(to_protocol(item));
    }
    out.range = to_protocol(input.range);
    return out;
}

inline DuduDuduAstDeclaration from_protocol(const protocol::Declaration& input) {
    DuduDuduAstDeclaration out;
    out.kind = static_cast<DuduDuduAstDeclarationKind>(input.kind);
    if (input.class_decl.has_value()) {
        out.class_decl = from_protocol(*input.class_decl);
    }
    if (input.enum_decl.has_value()) {
        out.enum_decl = from_protocol(*input.enum_decl);
    }
    if (input.function_decl.has_value()) {
        out.function_decl = from_protocol(*input.function_decl);
    }
    if (input.field_decl.has_value()) {
        out.field_decl = from_protocol(*input.field_decl);
    }
    if (input.constant_decl.has_value()) {
        out.constant_decl = from_protocol(*input.constant_decl);
    }
    if (input.implementation_decl.has_value()) {
        out.implementation_decl = from_protocol(*input.implementation_decl);
    }
    return out;
}

inline protocol::Declaration to_protocol(const DuduDuduAstDeclaration& input) {
    protocol::Declaration out;
    out.kind = static_cast<protocol::DeclarationKind>(input.kind);
    if (input.class_decl.has_value()) {
        out.class_decl = to_protocol(*input.class_decl);
    }
    if (input.enum_decl.has_value()) {
        out.enum_decl = to_protocol(*input.enum_decl);
    }
    if (input.function_decl.has_value()) {
        out.function_decl = to_protocol(*input.function_decl);
    }
    if (input.field_decl.has_value()) {
        out.field_decl = to_protocol(*input.field_decl);
    }
    if (input.constant_decl.has_value()) {
        out.constant_decl = to_protocol(*input.constant_decl);
    }
    if (input.implementation_decl.has_value()) {
        out.implementation_decl = to_protocol(*input.implementation_decl);
    }
    return out;
}

inline DuduDuduAstSourceOrigin from_protocol(const protocol::SourceOrigin& input) {
    DuduDuduAstSourceOrigin out;
    out.kind = static_cast<DuduDuduAstOriginKind>(input.kind);
    out.range = from_protocol(input.range);
    out.macro_name = input.macro_name;
    if (input.macro_identity.has_value()) {
        out.macro_identity = from_protocol(*input.macro_identity);
    }
    if (input.parent.has_value()) {
        out.parent = *input.parent;
    }
    return out;
}

inline protocol::SourceOrigin to_protocol(const DuduDuduAstSourceOrigin& input) {
    protocol::SourceOrigin out;
    out.kind = static_cast<protocol::OriginKind>(input.kind);
    out.range = to_protocol(input.range);
    out.macro_name = input.macro_name;
    if (input.macro_identity.has_value()) {
        out.macro_identity = to_protocol(*input.macro_identity);
    }
    if (input.parent.has_value()) {
        out.parent = *input.parent;
    }
    return out;
}

inline DuduDuduAstGeneratedDeclaration from_protocol(const protocol::GeneratedDeclaration& input) {
    DuduDuduAstGeneratedDeclaration out;
    out.declaration = from_protocol(input.declaration);
    out.origin = from_protocol(input.origin);
    return out;
}

inline protocol::GeneratedDeclaration to_protocol(const DuduDuduAstGeneratedDeclaration& input) {
    protocol::GeneratedDeclaration out;
    out.declaration = to_protocol(input.declaration);
    out.origin = to_protocol(input.origin);
    return out;
}

inline DuduDuduAstDiagnostic from_protocol(const protocol::Diagnostic& input) {
    DuduDuduAstDiagnostic out;
    out.severity = static_cast<DuduDuduAstDiagnosticSeverity>(input.severity);
    out.code = input.code;
    out.message = input.message;
    out.range = from_protocol(input.range);
    out.notes.reserve(input.notes.size());
    for (const auto& item : input.notes) {
        out.notes.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::Diagnostic to_protocol(const DuduDuduAstDiagnostic& input) {
    protocol::Diagnostic out;
    out.severity = static_cast<protocol::DiagnosticSeverity>(input.severity);
    out.code = input.code;
    out.message = input.message;
    out.range = to_protocol(input.range);
    out.notes.reserve(input.notes.size());
    for (const auto& item : input.notes) {
        out.notes.push_back(to_protocol(item));
    }
    return out;
}

inline DuduDuduAstExpansion from_protocol(const protocol::Expansion& input) {
    DuduDuduAstExpansion out;
    out.members.reserve(input.members.size());
    for (const auto& item : input.members) {
        out.members.push_back(from_protocol(item));
    }
    out.siblings.reserve(input.siblings.size());
    for (const auto& item : input.siblings) {
        out.siblings.push_back(from_protocol(item));
    }
    out.implementations.reserve(input.implementations.size());
    for (const auto& item : input.implementations) {
        out.implementations.push_back(from_protocol(item));
    }
    out.diagnostics.reserve(input.diagnostics.size());
    for (const auto& item : input.diagnostics) {
        out.diagnostics.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::Expansion to_protocol(const DuduDuduAstExpansion& input) {
    protocol::Expansion out;
    out.members.reserve(input.members.size());
    for (const auto& item : input.members) {
        out.members.push_back(to_protocol(item));
    }
    out.siblings.reserve(input.siblings.size());
    for (const auto& item : input.siblings) {
        out.siblings.push_back(to_protocol(item));
    }
    out.implementations.reserve(input.implementations.size());
    for (const auto& item : input.implementations) {
        out.implementations.push_back(to_protocol(item));
    }
    out.diagnostics.reserve(input.diagnostics.size());
    for (const auto& item : input.diagnostics) {
        out.diagnostics.push_back(to_protocol(item));
    }
    return out;
}

inline DuduDuduAstCapability from_protocol(const protocol::Capability& input) {
    DuduDuduAstCapability out;
    out.kind = static_cast<DuduDuduAstCapabilityKind>(input.kind);
    out.values.reserve(input.values.size());
    for (const auto& item : input.values) {
        out.values.push_back(item);
    }
    return out;
}

inline protocol::Capability to_protocol(const DuduDuduAstCapability& input) {
    protocol::Capability out;
    out.kind = static_cast<protocol::CapabilityKind>(input.kind);
    out.values.reserve(input.values.size());
    for (const auto& item : input.values) {
        out.values.push_back(item);
    }
    return out;
}

inline DuduDuduAstMacroDescriptor from_protocol(const protocol::MacroDescriptor& input) {
    DuduDuduAstMacroDescriptor out;
    out.name = input.name;
    out.entry_point = input.entry_point;
    out.accepted_kind = static_cast<DuduDuduAstDeclarationKind>(input.accepted_kind);
    if (input.attribute_schema.has_value()) {
        out.attribute_schema = from_protocol(*input.attribute_schema);
    }
    out.definition = from_protocol(input.definition);
    return out;
}

inline protocol::MacroDescriptor to_protocol(const DuduDuduAstMacroDescriptor& input) {
    protocol::MacroDescriptor out;
    out.name = input.name;
    out.entry_point = input.entry_point;
    out.accepted_kind = static_cast<protocol::DeclarationKind>(input.accepted_kind);
    if (input.attribute_schema.has_value()) {
        out.attribute_schema = to_protocol(*input.attribute_schema);
    }
    out.definition = to_protocol(input.definition);
    return out;
}

inline DuduDuduAstMacroCatalog from_protocol(const protocol::MacroCatalog& input) {
    DuduDuduAstMacroCatalog out;
    out.package = input.package;
    out.binary_identity = input.binary_identity;
    out.macros.reserve(input.macros.size());
    for (const auto& item : input.macros) {
        out.macros.push_back(from_protocol(item));
    }
    out.capabilities.reserve(input.capabilities.size());
    for (const auto& item : input.capabilities) {
        out.capabilities.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::MacroCatalog to_protocol(const DuduDuduAstMacroCatalog& input) {
    protocol::MacroCatalog out;
    out.package = input.package;
    out.binary_identity = input.binary_identity;
    out.macros.reserve(input.macros.size());
    for (const auto& item : input.macros) {
        out.macros.push_back(to_protocol(item));
    }
    out.capabilities.reserve(input.capabilities.size());
    for (const auto& item : input.capabilities) {
        out.capabilities.push_back(to_protocol(item));
    }
    return out;
}

inline DuduDuduAstHello from_protocol(const protocol::Hello& input) {
    DuduDuduAstHello out;
    out.compiler_version = input.compiler_version;
    out.protocol_version = input.protocol_version;
    out.schema_version = input.schema_version;
    out.max_frame_bytes = input.max_frame_bytes;
    return out;
}

inline protocol::Hello to_protocol(const DuduDuduAstHello& input) {
    protocol::Hello out;
    out.compiler_version = input.compiler_version;
    out.protocol_version = input.protocol_version;
    out.schema_version = input.schema_version;
    out.max_frame_bytes = input.max_frame_bytes;
    return out;
}

inline DuduDuduAstHelloAck from_protocol(const protocol::HelloAck& input) {
    DuduDuduAstHelloAck out;
    out.worker_version = input.worker_version;
    out.protocol_version = input.protocol_version;
    out.schema_version = input.schema_version;
    out.accepted = input.accepted;
    out.reason = input.reason;
    return out;
}

inline protocol::HelloAck to_protocol(const DuduDuduAstHelloAck& input) {
    protocol::HelloAck out;
    out.worker_version = input.worker_version;
    out.protocol_version = input.protocol_version;
    out.schema_version = input.schema_version;
    out.accepted = input.accepted;
    out.reason = input.reason;
    return out;
}

inline DuduDuduAstExpansionRequest from_protocol(const protocol::ExpansionRequest& input) {
    DuduDuduAstExpansionRequest out;
    out.macro_name = input.macro_name;
    out.declaration = from_protocol(input.declaration);
    out.invocation = from_protocol(input.invocation);
    out.compile_values.reserve(input.compile_values.size());
    for (const auto& item : input.compile_values) {
        out.compile_values.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::ExpansionRequest to_protocol(const DuduDuduAstExpansionRequest& input) {
    protocol::ExpansionRequest out;
    out.macro_name = input.macro_name;
    out.declaration = to_protocol(input.declaration);
    out.invocation = to_protocol(input.invocation);
    out.compile_values.reserve(input.compile_values.size());
    for (const auto& item : input.compile_values) {
        out.compile_values.push_back(to_protocol(item));
    }
    return out;
}

inline DuduDuduAstExpansionResponse from_protocol(const protocol::ExpansionResponse& input) {
    DuduDuduAstExpansionResponse out;
    out.expansion = from_protocol(input.expansion);
    out.cacheable = input.cacheable;
    out.external_input_hashes.reserve(input.external_input_hashes.size());
    for (const auto& item : input.external_input_hashes) {
        out.external_input_hashes.push_back(item);
    }
    return out;
}

inline protocol::ExpansionResponse to_protocol(const DuduDuduAstExpansionResponse& input) {
    protocol::ExpansionResponse out;
    out.expansion = to_protocol(input.expansion);
    out.cacheable = input.cacheable;
    out.external_input_hashes.reserve(input.external_input_hashes.size());
    for (const auto& item : input.external_input_hashes) {
        out.external_input_hashes.push_back(item);
    }
    return out;
}

inline DuduDuduAstWorkerError from_protocol(const protocol::WorkerError& input) {
    DuduDuduAstWorkerError out;
    out.code = input.code;
    out.message = input.message;
    out.diagnostics.reserve(input.diagnostics.size());
    for (const auto& item : input.diagnostics) {
        out.diagnostics.push_back(from_protocol(item));
    }
    return out;
}

inline protocol::WorkerError to_protocol(const DuduDuduAstWorkerError& input) {
    protocol::WorkerError out;
    out.code = input.code;
    out.message = input.message;
    out.diagnostics.reserve(input.diagnostics.size());
    for (const auto& item : input.diagnostics) {
        out.diagnostics.push_back(to_protocol(item));
    }
    return out;
}

} // namespace dudu::macro::sdk_bridge
